### PR TITLE
Add get_customer pre/post filters.

### PR DESCRIPTION
**Pull request by jtsternberg**
Allows finding customer records via other methods (other tables, etc).

Proposed Changes:
1. Adds a `edd_pre_get_customer` for short-circuiting the search.
2. Adds a `"edd_get_customer_by_{$field}"` and `edd_get_customer` filter at the bottom for filtering the result.

### CODE REVIEW

**Comment by jtsternberg** [comment]
I don't see any reason this PR would cause those tests to fail, but let me know if I need to update anything.

**Comment by cklosowski** [comment]
@jtsternberg It’s very likely not your changes causing this. I’ll take a look and test this out a bit. Thanks.

**Comment by jtsternberg** [comment]
Any thoughts on this?

**Comment by spencerfinnell** [comment]
@jtsternberg I like this idea and the test failures seem unrelated. The new filters need documentation though.

@cklosowski This seems like it would be fine to go in the next 2.x release.

**Comment by cklosowski** [comment]
I'm going to go ahead and merge this into the `release/2.9.23` branch (which is the next release). I'l open an issue to get documentation on them.

**Pull request merged**
