### PR TITLE
Add a new filter for the agree to terms HTML

### PR DESCRIPTION
**Pull request by gelform**
With the HTML hard coded, it can't be edited to include theme classes and HTM.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@gelform Are you just trying to filter the text for the terms or the entire HTML? If you're just trying to change the text, you can use this filter: `edd_get_option_agree_text`.

**Comment by gelform** [comment]
@pippinsplugins I want to be able to add custom css classes to the html. That's why I wrapped the whole thing.

**Comment by pippinsplugins** [comment]
Ok thanks. Milestoning for a future release.

**Comment by cklosowski** [comment]
Going to break this into an issue branch, just want to make a small change. Thanks @gelform, i'll keep your commit history in tact.

Issue is #5984

**Pull request closed without merging**
