### PR TITLE
Allow Order Items in Manual Creation to be Edited

### LINKED ISSUE #6789: 3.0: Individual item amounts need to be enterable when creating manual orders
When manually creating an order record, the individual item amounts (subtotal, tax, discount, and total) need to be enterable. Right now the amounts are all calculated automatically, which will work most of the time, but in cases where an admin needs to define custom amounts this will be a limitation.

The order adjustments feature does get close to providing the necessary flexibility, but not quite since those adjustments are order-specific, not order-item specific.

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #6789

Simplifies the Javascript by always working with input items to maintain values. `readonly` inputs are styled to look like plain text to dissuade this functionality from being used. It also moves the "Override" button below the Order Amounts metabox.

(to test latest JS be sure you run `npm run dev` -- compiled scripts are not committed for simpler diffs)

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@spencerfinnell could you resolve the merge conflicts on this PR please?

**Comment by pippinsplugins** [comment]
@spencerfinnell apologies, I'm not too familiar with webpack. When I run `npm run dev`, I get this:
```
> easy-digital-downloads@2.9.11 dev /var/www/html/wp/wp-content/plugins/easy-digital-downloads
> cross-env NODE_ENV=default webpack --watch

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! easy-digital-downloads@2.9.11 dev: `cross-env NODE_ENV=default webpack --watch`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the easy-digital-downloads@2.9.11 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pippin/.npm/_logs/2019-04-12T03_07_42_340Z-debug.log
```

Is that an install problem on my end or an issue in the branch?

**Comment by spencerfinnell** [comment]
Run `npm install` first.

**Comment by pippinsplugins** [comment]
Still throwing a bunch of errors, but now they're different:

>>>npm ERR! write after end

and

>>>> cross-env NODE_ENV=default webpack --watch

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! easy-digital-downloads@2.9.11 dev: `cross-env NODE_ENV=default webpack --watch`
npm ERR! spawn ENOENT

**Comment by cklosowski** [comment]
Looks like the merge conflict ended up putting 2.9.11 instead of the beta
3.0? For the package.json?

**Comment by spencerfinnell** [comment]
@cklosowski The version number is fine.

@pippinsplugins Try:

```
rm -rf node_modules
rm package-lock.json
npm cache clear --force
npm install
npm run dev
```

I committed a fresh build of all of the assets to this branch as well.

**Comment by pippinsplugins** [comment]
Thanks @spencerfinnell, between that and updating npm, I was able to get it.

**Pull request merged**
