### PR TITLE
Settings style improvements for labels and field section separators

### PR DESCRIPTION
**Pull request by DevinWalker**
This little PR adds style improvements to EDD Settings tabs. The CSS updates improve the label and field section separators. Here's a preview:
preview

I hope you like it! :)

### CODE REVIEW

**Comment by DevinWalker** [comment]
How do you guy's minify the stylesheets? I didn't see a grunt task for that. Do you use Codekit or something other?

**Comment by cklosowski** [comment]
@DevinWalker we'll take care of minification of them at a later time. No need for them to be in PRs. will put this PR on my list of things to test out this week.

**Comment by DevinWalker** [comment]
Sounds good. Thanks for taking a look at it. I also have some other changes in mind for the reports section similar to what we did in Give. I would love to discuss collaborating further on UX/UI

**Comment by pippinsplugins** [comment]
I really like the look of this

**Comment by cklosowski** [comment]
The only one I think is a little strange is the checkbox one. As it puts it below the checkbox when there is a ton of whitespace to the left, the rest looks great though

**Comment by pippinsplugins** [comment]
Let's go ahead and merge this in. We can make further improvements later. This is already a huge improvement.

**Comment by DevinWalker** [comment]
Great! I'll have more PRs coming soon.

**Comment by pippinsplugins** [comment]
Awesome!

**Pull request merged**
