### PR TITLE
We should allow for developers to run actions on a deleted option

### PR DESCRIPTION
**Pull request by chriscct7**

### CODE REVIEW

**Comment by pippinsplugins** [comment]
What about instead of passing the `$did_update`, we pass the old value.

Thoughts?

**Comment by chriscct7** [comment]
I think we should pass $did_update because in this context its more important than the old value, but we could add a second param for $old_value for those who want it

**Comment by pippinsplugins** [comment]
I was thinking `old_value` would be nice for times someone wants to run actions conditionally based on what the value was.

**Comment by chriscct7** [comment]
This is no longer required for the initial purpose I needed it for. Feel free to modify at will :)

**Comment by pippinsplugins** [comment]
Since not needed I'm going to punt to 2.5.4 just to help get 2.5 finished faster.

**Pull request closed without merging**
