### PR TITLE
Making sure that the cart item matches the post_parent

### PR DESCRIPTION
**Pull request by cklosowski**
Addresses #2978

### CODE REVIEW

**Comment by cklosowski** [comment]
Odd that this says it's failing...the build is passing.

**Comment by chriscct7** [comment]
Travis errored out on the push to the branch on a couple of them, but passed all builds on the pull request. When you push to a pull request, Travis does a complete run on both the pr and the branch. If either one fail or error you get a merge with caution warning. It's good to go.

**Comment by cklosowski** [comment]
:+1: thanks @chriscct7 Github must have made some updates, it didn't used to get this in depth in the Travis Data.

**Comment by chriscct7** [comment]
Yeah it didn't use to show both on GitHub, you used to have to hunt for Travis for this which is how I found out it did that in the first place. I don't think GitHub updated, but rather it appears Travis is finally taking advantage of being able to send multiple pull release status updates finally

**Pull request merged**
