### PR TITLE
edd_is_admin_page to support $page and $view

### PR DESCRIPTION
**Pull request by chriscct7**
Implements `edd_is_admin` as defined in #2657

Supports new customer management ui and reports page

### CODE REVIEW

**Comment by chriscct7** [comment]
@pippinsplugins can this be merged now?

**Comment by pippinsplugins** [comment]
No, absolutely not.

Not until @cklosowski and I have personally tested it extensively and we've evaluated it to see if it's the best approach.

**Comment by chriscct7** [comment]
I didn't mean merged as in like merge it now, was about 1am when I wrote that. I meant does anything else need to be done for it so we can move it along. I'd really like to use this in several of my extensions and if there's something that needs to be done, I just wanted to know so I could do it now, so it hopefully doesn't miss yet another release  *crosses fingers for 2.4*

**Comment by chriscct7** [comment]
Resubmitted as #3384

**Pull request closed without merging**
