### PR TITLE
Issue/6911 - Fix checkout inconsistencies

### LINKED ISSUE #6911: Checkout inconsistencies
I've noticed a number of inconsistencies at checkout that we can improve. Listed below are some of the issues I've spotted and examples.

## Legends
Some legends are sentence case, some are title case. E.g.

`Create an account (optional)`

vs

`Personal Info`
`Billing Details`
`Select Payment Method`
`Name on the Card`

## Placeholders
Some placeholders are sentence case, some are title case. E.g. 

`Email address`
`Confirm password`
`Card number`
`Your username or email address`
`Enter discount`

vs

`First Name`
`Last Name`
`Zip / Postal Code`

## Links
Some links at checkout have a period after the link, some don't. E.g.

`Have a discount code? Click to enter it`
`Already have an account? Login`

vs

`Need to create an account?	Register or checkout as a guest.`

## Error notices
Some error notices have a period at the end, some don't. E.g.

`Error: There is an error with the Amazon Payments configuration.`

vs

`Error: You must register or login to complete your purchase`

## Slashes
Some words in labels and placeholders contain spaces before and after slashes, some don't. E.g.

`Billing State / Province`
`Billing Zip / Postal Code`
`Zip / Postal Code`

vs

`Expiration (MM/YY)`

___

### Suggestions: 

**Legends, placeholders (and any labels)**

I propose we always use sentence case, where only the first word of the sentence is capitalized. Many sites I've seen use sentence case. It's easier on the eyes and looks friendlier. This looks strange: `Name on the Card`.

**Links**

I propose we do not include periods after links.

**Slashes**

I propose we remove any spaces from before and after slashes.

> Many people wonder whether to use a space before and after slashes in a sentence. The answer is typically no on both fronts. Spaces before slashes should be avoided. The only time it’s acceptable to use a space after a slash is when breaking up lines of a poem, song, or play.

Source: https://www.grammarly.com/blog/slash/

Amazon is a good example which demonstrates no spaces before and after slashes, Sentence case for labels, placeholders and legends:

screen shot 2018-09-05 at 6 12 52 pm

___

@easydigitaldownloads/core-team If we agree on the above I'll put together a PR. We'll need to go over our payment gateways also.

### PR DESCRIPTION
**Pull request by amdrew**
Fixes #6911

### CODE REVIEW

**Comment by JJJ** [comment]
Merged `release/3.0` in to make merging this WIP easier later. 👍

**Comment by pippinsplugins** [comment]
@amdrew do you have any other changes you wish to make here?

**Comment by amdrew** [comment]
@pippinsplugins Will take a look soon and let you know

**Comment by amdrew** [comment]
@pippinsplugins See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6911#issuecomment-436831456

That's all I can see for now in terms of the checkout. Feel free to merge once reviewed.

**Pull request merged**
