### PR TITLE
Free items do not go straight_to_gateway

### PR DESCRIPTION
**Pull request by cklosowski**
Addresses the concerns of #3068

### CODE REVIEW

**Comment by pippinsplugins** [comment]
This breaks the buy now process for me. It just adds it to the cart.

**Comment by pippinsplugins** [comment]
Confirmed that `master` still correctly processes the buy now.

**Comment by cklosowski** [comment]
...wasn't that the request of the ticket....?

**Comment by cklosowski** [comment]
Overview item 1 on the issue:
"When outputting the purchase_link shortcode, we verify if the item is free, and therefore change the edd_action_input to add_to_cart"

**Comment by pippinsplugins** [comment]
I meant it's breaking the buy now for non-free items, sorry.

**Comment by cklosowski** [comment]
@pippinsplugins Have a look when you can, fixed the issue you were seeing yesterday on the automatically generated buttons set to 'Buy Now'

**Comment by pippinsplugins** [comment]
Works beautifully.

**Pull request merged**
