### PR TITLE
Fix Airplane mode check #3287

### PR DESCRIPTION
**Pull request by juanfraa**
Airplane mode: In version 0.0.1, the method enabled didn’t exist. There
was a method named check_status() which returned ‘on’ and ‘off’.

If somebody using Airplane Mode 0.0.1 updates to the latest version of
EDD, the WP dashboard breaks up.

### CODE REVIEW

**Comment by chriscct7** [comment]
Looks good thanks! Just waiting for Travis to finish before we merge

**Comment by juanfraa** [comment]
Nice! Thanks.

**Comment by chriscct7** [comment]
Thanks @juanfraa!

**Comment by juanfraa** [comment]
Thank you @chriscct7 and all the team at EDD!

**Pull request merged**
