### PR TITLE
issue/6793 - Add `edd_insert_payment` hook.

### LINKED ISSUE #6793: 3.0: edd_insert_payment hook is missing
In latest `release/3.0`, the `edd_insert_payment` hook does not run. I think we need some backwards compatibility for this, as we use it in our own add-ons quite a bit and I know of a few custom integrations off the top of my head that rely on it.

### PR DESCRIPTION
**Pull request by sunnyratilal**
Fixes #6793.

### CODE REVIEW

**Comment by cklosowski** [comment]
@sunnyratilal, this PR does way more than just reintroducing the hook, is that intentional?

**Comment by mindctrl** [comment]
@sunnyratilal tested this with some custom code and with AffiliateWP and both worked as expected.

**Comment by sunnyratilal** [comment]
@cklosowski It's just cleanup, formatting, and DocBlock changes.  PHPStorm ran auto format on the file before I committed and I only noticed the large diff once I pushed.

**Comment by cklosowski** [comment]
👍 ok thanks @sunnyratilal

**Pull request merged**
