### PR TITLE
Improve batch processing to be extendable 

### PR DESCRIPTION
**Pull request by cklosowski**
#3561

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@cklosowski Could each of the file includes be in a single function using a switch statement instead of a separate function for each export type? A switch statement will be better for future expansions.

**Comment by cklosowski** [comment]
@pippinsplugins we could, but I think it makes it slightly more convoluted for people who want to either filter our default ones, or add their own ( by using our example ).

**Comment by pippinsplugins** [comment]
Are you thinking that by having them separate, we could allow people to replace our export classes?

**Comment by cklosowski** [comment]
Yes, it makes it so they can remove an action, and add their own to do an include for a specific type.

**Comment by cklosowski** [comment]
Or an extension builder can.

**Comment by pippinsplugins** [comment]
@cklosowski let's move `do_action( 'edd_batch_export_class_include', $form['edd-export-class'] );` to just after the nonce verification to ensure nothing can be executed during the process before we've verified it's legit.

**Pull request merged**
