### PR TITLE
Adding DCO to the CONTRIBUTING.MD file #7166

### LINKED ISSUE #7166: Add Developer Certificate of Origin to our CONTRIBUTING.MD file
A DCO is simply a _very_ short agreement that states, by committing this code, you have the right to do so, here is a link to the agreement:
https://developercertificate.org/

We'll just add that link to our `contributing.md` file. The basis of the agreement is (at the time of adding, version 1.1)
```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### PR DESCRIPTION
**Pull request by cklosowski**
Resolves #7166

Proposed Changes:
1. Adds a section to the `CONTRIBUTING.MD` that links to the DCO

### CODE REVIEW

**Comment by DrewAPicture** [comment]
@cklosowski Can we host our own copy of the DCO? I'm a little wary of blindly linking to a site that may or may not update itself in the future, which could potentially change the terms of contribution without us knowing it.

**Comment by cklosowski** [comment]
@DrewAPicture we can include it in the contributing MD if you think that's fine.

**Comment by cklosowski** [comment]
@SDavisMedia yeah, the goal will be to bring it to all repos, even private ones, as we have some non-sandhills members in them and we want to be sure that we're not unknowingly getting code from sources that haven't approved it's sharing.

**Comment by DrewAPicture** [comment]
@cklosowski Sure, it adds a bit of length but it's mainly just a repo-only file so that should be fine. I just don't love linking out to _somebody else's document_ 😉

**Comment by cklosowski** [comment]
Well not only that, it does lock us into a version, so if the version changes, we can remain on our specific version so we can be sure we're good with any changes.

**Comment by cklosowski** [comment]
Ok @DrewAPicture added it inline, and moved it down to the bottom before resources.

**Pull request merged**
