### PR TITLE
Issue/5234

### PR DESCRIPTION
**Pull request by stephywells**
#5239
#5234

### CODE REVIEW

**Comment by cklosowski** [comment]
Something is breaking the unit tests here and giving a response of `0` when we expect `1`
```
1) Tests_Customers::test_customer_notes
Failed asserting that 0 matches expected 1.
```

So either the test is broken, or the changes here are altering the response incorrectly.

**Comment by pippinsplugins** [comment]
@cklosowski It's failing because the array keys are getting reversed.

@stephywells Instead of adjusting `get_raw_notes()` I think we need to adjust `get_notes()` to ensure the parsing logic runs.

**Comment by stephywells** [comment]
Okay, I backed out the notes changes for now so the other changes can be accepted. That can be a separate PR.

**Comment by pippinsplugins** [comment]
Thanks! Will review / test soon.

**Comment by pippinsplugins** [comment]
@stephywells I've manually merged your branch into a new branch / PR so I could make a couple of additional adjustments. https://github.com/easydigitaldownloads/easy-digital-downloads/pull/5280

**Pull request closed without merging**
