### PR TITLE
Add localization to country and state strings.

### LINKED ISSUE #4934: Countries/States cannot be localized
Currently, the [country and state strings](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/country-functions.php) can not be localized apart from one exception: the [Spanish state strings](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/country-functions.php#L1567-L1621).

All country and state strings should be localizable, to allow the dropdown lists to be properly displayed in different locales.

### PR DESCRIPTION
**Pull request by schlessera**
Resolves #4934

### CODE REVIEW

**Comment by schlessera** [comment]
I'm not sure, do you want me to add the updated POT file to the pull request as well?

**Comment by michaelbeil** [comment]
Thanks @schlessera! Re the pot file, we can do that when we finalize the build for the next release.

**Comment by cklosowski** [comment]
I'm going to pull this PR into an issue branch, and get the merge conflict fixed up. Since the diff isn't viewable, that'll help me review the changes, probably a formatting issue.

**Comment by cklosowski** [comment]
Closing in favor of #4978 as it fixes a merge conflict.

**Comment by cklosowski** [comment]
@schlessera your commit history is in tact, thanks for the updates. I'll regenerate the translation files as we near release.

**Pull request closed without merging**
