### PR TITLE
issue/5791 - Add `Enable Product Reviews` button

### PR DESCRIPTION
**Pull request by sunnyratilal**
#5791

### CODE REVIEW

**Comment by cklosowski** [comment]
If we're adding a button here when Reviews does not exist, we should also add it when it does exist, but instead of linking, it should actually enable reviews. I'd be pretty confused if I didn't have Reviews installed, went and purchased, installed and activated, and now that button was missing.

So I think that Reviews needs to have an update to make a media button as well, but when activated it allows you to one click enable them.

**Comment by pippinsplugins** [comment]
I don't think I agree with putting this in the media buttons. Instead I think it should be a metabox like the standard reviews box (enable / close) is when Reviews is active.

**Comment by cklosowski** [comment]
@pippinsplugins that's what @sunnyratilal and I agreed to within Slack the other day too. It simply just makes the same metabox that would exist if Reviews is active, and once Reviews is active, EDD Core does not register it.

**Comment by pippinsplugins** [comment]
:+1:

**Pull request merged**
