### PR TITLE
Update manual gateway label

### LINKED ISSUE #7067: Add a 'Manual' gateway option when adding a payment
### Explain your enhancement (please be detailed)
Add a 'manual' option for the gateway dropdown when adding a payment manually.

### Justification or use case
Right now our gateways listed there are only ever the registered gateways, including 'Test Payment'. If however you choose to manually create a payment for a customer for some reason, but don't want to assign it to a gateway like Stripe, and don't want 'Test Payment' to show up to the user on the front end, we should have a 'Manual'.

We had this come up previously with #6063 when doing filters.

### LINKED ISSUE #7848: 3.0 - Free Purchases Show Incorrrect Gateway in Orders List Table
### Expected behavior
When I view the Orders table, I expect to see the correct gateways.

### Actual behavior
Free purchases show as "Test Payment" in the orders list table. The gateway does show correctly as "Free Purchase" on the order details and customer details screens.

### Steps to reproduce the behavior
1) Create a free download and sell it.
2) View the order in the orders list table--it shows "Test Payment" as the gateway.
3) Click on the order to view the details--it shows "Free Purchase" as the gateway.
4) Click "View customer record" to view the customer details--the order shows as "Free Purchase" as the gateway.

### Information (if a specific version is affected):
PHP Version: 7.3.5
EDD Version (or branch): 3.0
WordPress Version: 5.4.1

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #7067
Fixes #7848

### CODE REVIEW

**Comment by ashleyfae** [comment]
These unit tests need updating:

```
There were 2 failures:
1) Test_Gateways::test_payment_gateways
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Test Payment'
+'Store Gateway'
/home/travis/build/easydigitaldownloads/easy-digital-downloads/tests/tests-gateways.php:25

2) Test_Gateways::test_get_gateway_admin_label
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Test Payment'
+'Store Gateway'
/home/travis/build/easydigitaldownloads/easy-digital-downloads/tests/tests-gateways.php:96
```

**Comment by robincornett** [comment]
@ashleyfae should the gateway checkout label ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/7067/includes/gateways/functions.php#L206)) also be updated to `Store Gateway`?

**Comment by ashleyfae** [comment]
> @ashleyfae should the gateway checkout label ([ref](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/issue/7067/includes/gateways/functions.php#L206)) also be updated to `Store Gateway`?

Yes, I think so.

**Comment by ashleyfae** [comment]
Code-wise this looks good. Left a comment on the issue though: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7067#issuecomment-651135457

**Comment by ashleyfae** [comment]
Restarted the failed unit test. Feel free to merge if/when that passes. :+1:

**Pull request merged**
