### PR TITLE
issue/7539 - Respect Currency Settings and Adjust Calculations

### LINKED ISSUE #7539: 3.0 - Orders - Amounts Don't Respect Currency Symbol Position
### Expected behavior

When viewing the Order Amounts the amounts should respect the sitewide currency settings.

### Actual behavior

The symbol is forced to the left.

### Steps to reproduce the behavior
1) Create an order with an order item.

### Information (if a specific version is affected):
EDD Version (or branch): `release/3.0`

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #7539 

Proposed Changes:
1. Ensure site currency settings are respected on Order screens.

---

Notes:

- Run `npm install & npm run dev`.
- Some symbols will be doubled until #7540 is merged
- Styles for right-aligned symbols isn't perfect on the Order Items table, but can be iterated later

### CODE REVIEW

**Comment by spencerfinnell** [comment]
@pippinsplugins Not sure what you are referring to there?

**Comment by pippinsplugins** [comment]
> @pippinsplugins Not sure what you are referring to there?

The Order Amounts metabox does not respect the currency position settings settings. To see this, set your currency position to AFTER. My screenshot above is on a site where the position has been set to AFTER.

**Comment by spencerfinnell** [comment]
@pippinsplugins This PR fixes the symbols on the Order Item line items and the calculations when adding an item. If you add an item when creating an order you'll see doubled up symbols currently:

Screen Shot 2020-02-07 at 9 48 29 AM

My settings have currency position after.

https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7540 covers the removal of the static symbol when adjusting the labels/values.

It's a little fractured to test unfortunately, but I tried to keep things grouped in the order I was updating that made sense.

**Comment by pippinsplugins** [comment]
Ah, I missed https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7540.

All good then.

**Comment by spencerfinnell** [comment]
This can likely be ignored while https://github.com/easydigitaldownloads/easy-digital-downloads/issues/7582 is in progress, and most likely eventually closed.

**Comment by spencerfinnell** [comment]
Closing in favor of #7599 which includes a `Currency` package with tests that handles formatting numbers and currency.

**Pull request closed without merging**
