### PR TITLE
Add download name helper function.

### PR DESCRIPTION
**Pull request by pderksen**
Not a must-have, but would help the readability of some of my custom EDD filters.

### CODE REVIEW

**Comment by JeroenSormani** [comment]
I'd suggest moving this to the `EDD_Download` class, the loose functions aren't actively developed/added anymore if I'm correct. 

May not be a bad idea to have a specific method for that as `$download->__get( 'post_title' );` kinda looks rubbish

**Comment by cklosowski** [comment]
I vote for in `EDD_Download` as well.

**Comment by pippinsplugins** [comment]
I as well.

**Comment by pderksen** [comment]
That work?

**Comment by pippinsplugins** [comment]
I like it.

@cklosowski ?

**Comment by cklosowski** [comment]
Yep! Merging.

**Pull request merged**
