### PR TITLE
Add install tests

### PR DESCRIPTION
**Pull request by JeroenSormani**
Hey,

Adding tests for `includes/install.php`

Almost 100% testing the file, just not two lines; http://cl.ly/image/1t3F242Y0L08

I can't think of a way to test this, you guys have an idea?

Cheers,
Jeroen

### CODE REVIEW

**Comment by chriscct7** [comment]
Nice work!

You can  run a $this->assertFileExists( ) to ensure the .htaccess file exists inside the wp-content/uploads/edd/ folder

**Comment by pippinsplugins** [comment]
@JeroenSormani You are quickly moving up the list of people I owe drinks to. Thank you so much for this!

**Comment by JeroenSormani** [comment]
Nice :smile:, I try to do as much as I can.

@chriscct7 I see the assertFileExists is already done here; https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/tests/tests-easy-digital-downloads.php#L42

I don't think that will cover that line in the coverage report, right?

**Comment by pippinsplugins** [comment]
For testing that file, are you just trying to test that it exists?

**Comment by JeroenSormani** [comment]
Not even specific (since its already tested before), I just want those two lines covered for the 100% coverage.

So the challenge is to get inside that `if` statement. (Where I don't see a way for)

**Comment by pippinsplugins** [comment]
Oh I see what you mean. Hmm. That function already exists so the file doesn't need to be loaded.

This might just be a case where we can't get to 100%.

**Comment by pippinsplugins** [comment]
@cklosowski I'm happy with this if you are too.

**Comment by cklosowski** [comment]
Yeah looks solid. I'll go ahead and merge. Thanks @JeroenSormani!

**Pull request merged**
