### PR TITLE
Add "edd_price_options_classes" Filter

### PR DESCRIPTION
**Pull request by mintplugins**
This change makes an array for the css classes which will be used for the edd_price_options div. It is filterable using "edd_price_options_classes" and sanitized using sanitize_html_class

### CODE REVIEW

**Comment by mintplugins** [comment]
#4669

**Comment by pippinsplugins** [comment]
@mintplugins a couple of nitpicky things:

1. There should always be a space after `//` for comments
2. The default value for the classes should be an empty string instead of null since the datatype we're setting in the filter is a string.
3. Let's please add `esc_attr()` to the class output (around `rtrim()`).

**Comment by pippinsplugins** [comment]
The `foreach( $css_classes_array as $css_class ) {` could also be simplified to this:
```php
$css_classes_string = array_map( 'sanitize_html_class ', implode( $css_classes_array, ' ' ) );
```

**Comment by mintplugins** [comment]
@pippinsplugins Good catches, thanks. I just had to put the implode around the array_map since it must be passed an array and implode creates a string.

`
$css_classes_string = implode( array_map( 'sanitize_html_class', $css_classes_array ), ' ' );
`

**Comment by shazahm1** [comment]
Since `sanitize_html_class()` is being used, there is no need to run `esc_attr()` on the imploded string. Basing this on how core does pretty much the same with `get_body_class()` and `body_class()`.

**Comment by mintplugins** [comment]
@shazahm1 That definitely true. I think we are going to leave it in now since escaping should be done as close to the actual output as possible and future changes to this could possible change how it functions. Having that last esc_attr doesn't necessarily hurt anything so I would argue it's better to have it in there.

**Pull request merged**
