### PR TITLE
Add update notifications to system info

### PR DESCRIPTION
**Pull request by ghost1227**
Love it!

#3776

### CODE REVIEW

**Comment by spencerfinnell** [comment]
Cool! What about translations?

**Comment by chriscct7** [comment]
Yeah we don't want those translated ;)

**Comment by pippinsplugins** [comment]
Loks great!

**Comment by pippinsplugins** [comment]
I'd say merge this in @cklosowski !

**Comment by chriscct7** [comment]
:shipit:

**Comment by pippinsplugins** [comment]
@chriscct7 lol is that a custom emoji?

**Comment by cklosowski** [comment]
:heart: this. Merging.

**Pull request merged**
