### PR TITLE
reposition purchase link shortcode #3726

### LINKED ISSUE #3726: Purchase Shortcode placement on edit screen
Sorry, I missed this issue: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3339 

Just wondering why something like this wasn't considered.

screen shot 2015-08-19 at 2 12 41 am

That seems like the most logical placement to me. I'm only thinking of this because I honestly I don't like its placement in the Download Settings. It's not a setting and for it to be something that appears after a download is created, I don't think it should be halfway down the screen in a settings metabox.

Thoughts? Close if I'm a weirdo!

### PR DESCRIPTION
**Pull request by SDavisMedia**
Resolves #3726

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@SDavisMedia let's move this to `release/2.6`

**Comment by SDavisMedia** [comment]
That works. For now my branch just sits until there's a branch for 2.6 right?

**Comment by pippinsplugins** [comment]
@SDavisMedia No, I typed that wrong. Meant `release/2.5`.

**Comment by pippinsplugins** [comment]
@SDavisMedia Wait, yes, I was right the first time. `release/2.6` please

**Pull request closed without merging**
