### PR TITLE
Add the product id in the sales api.

### PR DESCRIPTION
**Pull request by wolfkang**
Add the product id in the sales api to fetch the product information after calling the sales api.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
`$item['id']` should be correct here. Why are you proposing changing it to `$item_id`?

**Comment by chriscct7** [comment]
@pippinsplugins $item_id is actually more correct. See about 10 lines above. We do a check in case the $item variable isn't an array but just a number.

**Comment by cklosowski** [comment]
Yes, `$item_id` is actually more correct due to this line:
`$item_id  = isset( $item['id']    ) ? $item['id']    : $item;`

**Comment by cklosowski** [comment]
Thanks @wolfkang

**Pull request merged**
