### PR TITLE
Introduce class `EDD_Customer_Query`

### PR DESCRIPTION
**Pull request by felixarntz**
This PR introduces the new `EDD_Customer_Query` class (as described in #5448 before) and makes use of it in the `EDD_DB_Customers` methods `get_customer_by()`, `get_customers()` and `count()`.

The class uses a simple caching layer for its queries to boost performance, therefore a bit of other related functionality has been introduced as well (in particular the methods `set_last_changed()` and `get_last_changed()` in `EDD_DB_Customers`. A few new properties on the `EDD_DB_Customers` class have been introduced as well.

I tried to make the query class more flexible than the current query method, thus handled a few query variables differently. However, when creating a query instance through one of the methods that already existed before, all the arguments are automatically "translated" to the `EDD_Customer_Query` ones so that things are backward-compatible.

I did not do extensive testing yet, only basic tests in EDD, so that still needs to be done. So there still needs to be some work done for this PR, but I already opened it for first review/feedback.

### CODE REVIEW

**Comment by felixarntz** [comment]
I noticed several unit tests started failing after this. I fixed a few issues I encountered and looked into what might cause these issues, but couldn't figure it out yet. When using the class and its surrounding functions in the admin, things worked fine.

I'm not familiar with how the EDD test suite is set up, some help would be much appreciated. :)

**Comment by sunnyratilal** [comment]
Looks like a corrupt `MySQL` table

**Comment by cklosowski** [comment]
Changed the base to `release/2.8`

**Comment by cklosowski** [comment]
Going to start looking into this PR, might be necessary to close it and pull it into an issue branch within the organization, but rest assured @felixarntz your commit history will stay in tact if I do that. I appreciate the work you've done here. 👍 🔥

**Comment by felixarntz** [comment]
@cklosowski Thanks! There was one issue I couldn't resolve when I wrote the code - let me know if you have questions about anything.

**Comment by cklosowski** [comment]
Opening up as an issue branch to fix a few things.

**Pull request closed without merging**
