### PR TITLE
Fixes the use of the post_status key in edd_get_purchase_link

### PR DESCRIPTION
**Pull request by chriscct7**
Solves #3144 and corrects a docbloc

### CODE REVIEW

**Comment by cklosowski** [comment]
There is zero need for this:
```$download = WP_Post::get_instance( $_id );``` is used when instantiating the `EDD_Download` class, and by that, brings in the `post_status` attribute.

Tested it out myself:
```
$download = new EDD_Download( 74 );
var_dump($download->post_status);
```

Result: `string(7) "publish"``

It's set in this process:
```
foreach ( $download as $key => $value ) {

	$this->$key = $value;

}
```

**Comment by chriscct7** [comment]
Scutinizer doesn't seem to like the fact that the key isn't declared for the class. I think we should add the key declaration to the class so other developers looking at that class know its there.

**Comment by pippinsplugins** [comment]
What's the actual error scrutinizer is giving?

**Comment by pippinsplugins** [comment]
Closing this and fixing in a new PR.

**Pull request closed without merging**
