### PR TITLE
Unit tests class-edd-customer.php [WIP]

### PR DESCRIPTION
**Pull request by JeroenSormani**
I'm still working on it, so do not merge just yet :smile:

### CODE REVIEW

**Comment by pippinsplugins** [comment]
:)

**Comment by cklosowski** [comment]
@JeroenSormani can you tell me why we have a separate new file in this PR for testing the customer class, when we have https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/tests/tests-customers.php ?

**Comment by JeroenSormani** [comment]
FML. @cklosowski because I am a total idiot.

The code coverage report only showed a low amount of code coverage. I did check if there already was a file, but I related that test file with the db-customer**s**.php file. :disappointed:

**Comment by cklosowski** [comment]
Ah @JeroenSormani no worries, however if code coverage is low, by all means, let's get as much coverage into that existing file as we can. Love the unit tests you've been adding :)

**Comment by JeroenSormani** [comment]
Closing, no need to keep open.

**Pull request closed without merging**
