### PR TITLE
Add filter around nginx redirect warning

### PR DESCRIPTION
**Pull request by mintplugins**
#7259

### CODE REVIEW

**Comment by spencerfinnell** [comment]
@mintplugins What about checking for an environment variable that hosts could add to the `wp-config.php` as well? Similar to how core allows the PHP upgrade button to be taken over: https://github.com/WordPress/WordPress/blob/9785381a8c7bdf668f49d2606aee8224515da447/wp-includes/functions.php#L6990

**Comment by mintplugins** [comment]
@spencerfinnell I haven't used PHP environment vars before. Would you need to use `putenv` in the wp-config file to set it? If so, why use that as opposed to a constant, similar to WP_DEBUG?

**Comment by spencerfinnell** [comment]
@mintplugins Sorry you're right, it wouldn't be added to `wp-config.php`, it would be set through something like `putenv` or `$_ENV`

**Comment by mintplugins** [comment]
Ah interesting. The environment var can be set at the php-fpm level, avoiding the need for any MU plugins or wp-config.php changes. Hosts will probably prefer that. I'll add it.

**Comment by mintplugins** [comment]
@spencerfinnell I am having a bit of trouble figuring out how to make it default to true if it is not set. 

I am thinking we would have to use "no" instead of an actual boolean to accomplish this, as an empty or unset value comes through as falsey.

**Pull request merged**
