### PR TITLE
Replace soon-to-be-deprecated user function with current equivalent

### LINKED ISSUE #4096: Remove usage of get_currentuserinfo()
WordPress 4.5 is deprecating the `get_currentuserinfo()` function: https://core.trac.wordpress.org/ticket/19615

We use it in one place: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/d02aefe0d5d9b82c70e2a44880d1bafd191897c9/includes/gateways/functions.php#L259

Let's get rid of it.

### PR DESCRIPTION
**Pull request by brashrebel**
Closes #4096

### CODE REVIEW

**Comment by brashrebel** [comment]
Looks like [this line](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/tests/tests-api.php#L244) is where it is failing? I'm confused.

**Comment by pippinsplugins** [comment]
Sweet, we'll get this merged in after 2.5 goes out.

**Comment by cklosowski** [comment]
@brashrebel if you just merge master into your branch it should resolve your test woes:

```
> git checkout master
> git pull origin master
> git checkout issue/4096
> git merge master
> git push origin issue/4096
````
And we should be good, I just checked out the PR and did that and things passed with flying colors :)

**Comment by pippinsplugins** [comment]
@brashrebel Think you could update this?

**Pull request merged**
