### PR TITLE
Ignore the ajax works test if Airplane mode is active

### PR DESCRIPTION
**Pull request by chriscct7**
Solves #3215

### CODE REVIEW

**Comment by pippinsplugins** [comment]
I don't think this is done right. It shouldn't set the transient if airplane mode is active. Instead it should short circuit the remote request and just return `true`.

**Comment by chriscct7** [comment]
If you do that then Airplane mode will be checked on every single admin page viewing for those using Airplane mode. That would slow the localhost down alot, even though we know it works

**Comment by chriscct7** [comment]
Unless what you want to do is move the airplane mode check above the remote request. We could do that and solve the problem.

**Comment by pippinsplugins** [comment]
I'm doing the airplane mode check before the request is made. I have an updated commit almost ready.

**Comment by chriscct7** [comment]
Ok

**Comment by pippinsplugins** [comment]
@cklosowski Take a look at this and let me know if you are happy with it.

**Comment by pippinsplugins** [comment]
@chriscct7 too

**Comment by pippinsplugins** [comment]
Resubmitting against master.

**Pull request closed without merging**
