### PR TITLE
Add default value of -1 to multicheck, gateway, and payment icon settings fields - issue/4928

### PR DESCRIPTION
**Pull request by pippinsplugins**
#4928

### CODE REVIEW

**Comment by spencerfinnell** [comment]
`Notice: Undefined variable: html in /Users/spencerfinnell/dev/astoundify/wp-content/plugins/easy-digital-downloads/includes/admin/settings/register-settings.php on line 1367`

**Comment by pippinsplugins** [comment]
Notice fixed!

**Comment by spencerfinnell** [comment]
Perfect 👍

**Comment by pippinsplugins** [comment]
Will merge once tests pass.

**Pull request merged**
