### PR TITLE
Honor posted discounts when Apply isn't clicked

### PR DESCRIPTION
**Pull request by cklosowski**
Addresses #2895. Will only apply if no discounts are on the cart OR multiple discounts are allowed.

### CODE REVIEW

**Comment by cklosowski** [comment]
@pippinsplugins you are commenting on old commits ;) look at the 'Files changed' area.

**Comment by pippinsplugins** [comment]
Doh!

**Comment by cklosowski** [comment]
I took your advice and found a better way to do this, that was less 'hackish'

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@cklosowski Can you link up the commits?

**Comment by cklosowski** [comment]
No extra commits, just making sure we're good on this. I know we had a couple discussions about how to handle this.

**Pull request merged**
