### PR TITLE
Added new filter for payment's default currency

### PR DESCRIPTION
**Pull request by daigo75**
Ref. [#4164 - New feature - Filter for payment's default currency](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/4164).

### CODE REVIEW

**Comment by daigo75** [comment]
@pippinsplugins Just checking if this hook is going to be included in EDD (eventually with some alterations), so that I can write a filter for it. Thanks.

**Comment by pippinsplugins** [comment]
Yes. It's currently milestoned for 2.6. If it's important to you, I can bump it up to an earlier release.

**Comment by daigo75** [comment]
It should not be critical, but the sooner, the better. Thanks. :)





On Sun, Jan 24, 2016 at 12:13 AM -0800, "Pippin Williamson" <notifications@github.com> wrote:





Yes. It's currently milestoned for 2.6. If it's important to you, I can bump it up to an earlier release.

---

**Comment by cklosowski** [comment]
I'm going to move from `2.6` to `2.5.8` the change is pretty clear, but `2.5.7` is getting prepped for some bug fixes before we start adding features.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by daigo75** [comment]
:+1:

**Pull request merged**
