### PR TITLE
Validate credit card number using Luhn

### PR DESCRIPTION
**Pull request by benjaminprojas**
@pippinsplugins This validates whether the credit card number is valid based on the luhn algorithm.  This also validates the expiration date, making sure that the month + year are >= the current month.  

This can be used by all gateways using the default purchase form.

### CODE REVIEW

**Comment by cklosowski** [comment]
We should get some unit tests around these added functions if we are going to merge them.

**Comment by benjaminprojas** [comment]
@cklosowski sounds good.  @pippinsplugins asked me to make this PR so whatever needs to happen is fine with me.

**Comment by cklosowski** [comment]
:+1:

**Comment by benjaminprojas** [comment]
@pippinsplugins actually, just realized that this will fail for any gateway who does not use the purchase form. With PayPal Express I am not displaying the CC form like so:

```php
add_action( 'edd_paypalexpress_cc_form', '__return_false' );
```

Would something similar work to avoid validation here? I imagine we would want to bypass the entire edd_purchase_form_validate_cc() function.

**Comment by pippinsplugins** [comment]
@benjaminprojas This should probably get called by the payment gateway and not automatically by core. It's really here as a helper function so that gateways don't have to do it themselves, but the gateway will still need to call it.

**Comment by benjaminprojas** [comment]
@pippinsplugins that totally makes sense.  I'll make the changes and push it out.

**Comment by pippinsplugins** [comment]
Great, ping me when ready.

**Comment by benjaminprojas** [comment]
@pippinsplugins okay I pulled out the automatic validation.  Now just the helper functions remain... should be good to go.

**Comment by cklosowski** [comment]
Once merged, let's make sure #3502 get's completed

**Comment by benjaminprojas** [comment]
@pippinsplugins I see this isn't in the beta 1 for EDD 2.4.  Are we still planning this for 2.4?

**Comment by chriscct7** [comment]
@benjaminprojas yeah @cklosowski is working on this and #3502

**Comment by cklosowski** [comment]
@benjaminprojas I've taken your basis and extended it, there were a few issues with regular expressions that weren't working on a couple card types. I've also made it a single function to call for developers to use that goes through the process. Also shortens the loop of card types once once is found and returns it, so we don't continue looping if the first card type is found.

**Comment by cklosowski** [comment]
Once it's approved in the PR I've submitted we'll Props you on it

**Comment by pippinsplugins** [comment]
Closing since it's being done through #3502

**Pull request closed without merging**
