### PR TITLE
Make state field select instead of text if possible

### PR DESCRIPTION
**Pull request by brashrebel**
If applicable, this gets the states for the given country and makes the state field on the profile editor a select field instead of just plain text.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Looks good to me at first glance.

**Comment by sdmtt** [comment]
I tested this and it works fine, but the field should be updated when the country is changed (`admin-ajax.php?action=edd_get_shop_states`).

**Comment by pippinsplugins** [comment]
@brashrebel Would you be up for updating for the comment above?

**Comment by brashrebel** [comment]
@pippinsplugins yep! I'll get on that soon.

**Comment by brashrebel** [comment]
@pippinsplugins I took a stab at this and was unsuccessful. Think you can point me in the right direction? I have very little ajax experience. I know that in the admin and on the checkout screen there are .js files which include functions for this but there's nothing on the profile editor page to use. Just need a little guidance.

**Comment by pippinsplugins** [comment]
@brashrebel I'm not 100% what is needed here. Will review more after 2.5 is out.

**Comment by cklosowski** [comment]
Pulling this into a new branch and PR to merge directly into `release/2.6` and make any necessary updates.

**Pull request closed without merging**
