### PR TITLE
issue/6290 - (WIP) Initial pass at autoloader

### PR DESCRIPTION
**Pull request by afragen**
Still very rough.

#6290

### CODE REVIEW

**Comment by afragen** [comment]
@cklosowski @DrewAPicture wanna take a look at this. Working fine on my end. 

I/We may need to make a few adjustments to use same autoloader for EDD_SL but maybe just include a slightly different version. I haven't worked on that part yet.

**Comment by DrewAPicture** [comment]
@cklosowski @JJJ can correct me if I'm wrong, but I was under the impression initial plan was introduce the autoloader much lower in the stack to autoload _specific_ files or directories only and no rework the entire base class. This feels like a pretty heavy approach.

**Comment by afragen** [comment]
Sorry if I over extended. This autoloader doesn't autoload all files, only classes.

**Comment by afragen** [comment]
I guess I mean allow for PSR-4 loading if that sort of file renaming occurs.

**Comment by afragen** [comment]
I think I've actually gotten it to work with EDD and EDD_SL.

**Comment by JJJ** [comment]
Hey all,

I've reviewed this PR, and while I agree with @DrewAPicture that it's a lot to take in, the work done here is both impressive and comprehensive. It would be a shame for it to go unnoticed, so I want to thank @afragen for taking the time to work this all out.

The only reason that I do not want to merge this as is, is because the long term goal is to normalize _all_ of the file names and locations into an easier to understand and work-with pattern, and that will offset the need for a lot of the complexity that was necessary here.

----

There are still a number of add-ons that choose to include EDD files directly, and while I personally do not want to endorse that type of coding for very much longer, we will need time to communicate to those plugin authors to avoid breaking sites for users.

As we continue to work more on EDD 3.0, this PR will become increasingly more stale, and merging is going to become more and more difficult, and realistically, unlikely.

I don't want to abandon Andy's efforts, but I also don't want to keep expectations lingering around that this will be the approach that we end up taking when it seems like it may not be.

I'd like to recommend that we close this pull request without merging, and revisit the approach used here for EDD 3.1 or after. Pinging @pippinsplugins @cklosowski for a consult.

**Comment by pippinsplugins** [comment]
@JJJ I can agree on all your sentiments above. Thanks @afragen!

**Comment by afragen** [comment]
@pippinsplugins @jjj your are both/all quite welcome. It was a fun exercise and I learned a bunch in doing it.

**Pull request closed without merging**
