### PR TITLE
Widget tests

### PR DESCRIPTION
**Pull request by JeroenSormani**
Unit tests for widgets.php

Still work in progress, need to do the third widget.

### CODE REVIEW

**Comment by JeroenSormani** [comment]
Just added the tests to get 100% coverage for this file.

**Comment by pippinsplugins** [comment]
Looks great to me.

Using `assertContains` is the best option I'm aware of for testing output.

**Comment by JeroenSormani** [comment]
Fixed two new failures in the tests.

**Comment by pippinsplugins** [comment]
@JeroenSormani awesome! Is this finished now or is there still another widget to add?

**Comment by JeroenSormani** [comment]
Its finished, just checked the code and do see the three widgets in there. 

Having some annoying issues with xDebug so can't run coverage reports :disappointed:

**Comment by pippinsplugins** [comment]
:D

**Comment by pippinsplugins** [comment]
Could you update the `@since` tags to `2.4.3`?

**Comment by JeroenSormani** [comment]
Done

**Comment by pippinsplugins** [comment]
Thanks!

**Pull request merged**
