### PR TITLE
Add edd_items_in_cart cookie on add to cart

### PR DESCRIPTION
**Pull request by davekiss**
If this cookie doesn't exist before the next page loads, users could potentially see a cached page on systems that check for the cookie's presence before serving uncached content.

Also needs to be added to the minified js file.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@davekiss Were you still interested in adding the localized approach?

**Comment by pippinsplugins** [comment]
Closing due to lack feedback. @davekiss if you're still interested in this, let me know!

**Comment by grappler** [comment]
@pippinsplugins I am interested in looking into this. If the cookie is not set when adding the download to the cart then the site will continue to serve the cached pages till the visitors views a non-cached page which will set the cookie.

**Comment by pippinsplugins** [comment]
@grappler I'd be more than happy to revisit it.

**Pull request closed without merging**
