### PR TITLE
Script tests

### PR DESCRIPTION
**Pull request by JeroenSormani**
Wow, I've been lacking in doing commits lately!

Gonna try picking it up again :smile: 

This script has two `markTestIncomplete`, as it is generating some errors;
The error only occur when testing the full suite, not when only testing the tests-scripts.php file.

Maybe you got an idea why its happening (happens on the lines with `$this->go_to( get_permalink(..) );`

```
There were 2 errors:

1) Tests_Scripts::test_load_scripts_checkout
Trying to get property of non-object

/private/tmp/wordpress/wp-includes/query.php:4349
/private/tmp/wordpress/wp-includes/query.php:496
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/checkout/functions.php:78
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/plugin-compatibility.php:134
/private/tmp/wordpress/wp-includes/plugin.php:571
/private/tmp/wordpress/wp-includes/query.php:1817
/private/tmp/wordpress/wp-includes/query.php:2364
/private/tmp/wordpress/wp-includes/query.php:3836
/private/tmp/wordpress/wp-includes/class-wp.php:540
/private/tmp/wordpress/wp-includes/class-wp.php:611
/private/tmp/wordpress-tests-lib/includes/testcase.php:359
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/tests/tests-scripts.php:30

2) Tests_Scripts::test_register_styles_checkout_ssl
Trying to get property of non-object

/private/tmp/wordpress/wp-includes/query.php:4349
/private/tmp/wordpress/wp-includes/query.php:496
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/checkout/functions.php:78
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/includes/plugin-compatibility.php:134
/private/tmp/wordpress/wp-includes/plugin.php:571
/private/tmp/wordpress/wp-includes/query.php:1817
/private/tmp/wordpress/wp-includes/query.php:2364
/private/tmp/wordpress/wp-includes/query.php:3836
/private/tmp/wordpress/wp-includes/class-wp.php:540
/private/tmp/wordpress/wp-includes/class-wp.php:611
/private/tmp/wordpress-tests-lib/includes/testcase.php:359
/Applications/MAMP/htdocs/edd/wp-content/plugins/Easy-Digital-Downloads/tests/tests-scripts.php:85
```

### CODE REVIEW

**Comment by pippinsplugins** [comment]
This is awesome :)

Looks like the non-object error is coming from `edd_is_success_page()`, perhaps due to the settings page not being set?

**Comment by JeroenSormani** [comment]
@pippinsplugins the error had to do with the `edd_is_success_page()` call within the `edd_disable_404_redirected_redirect()`. Pretty strange, but the `get_queried_object` was not set (`null`) at that call. 

Therefore I've moved the `parse_query` hook to `template_redirect`, just before the hook it wants to remove. See https://github.com/JeroenSormani/Easy-Digital-Downloads/commit/68268ad7f01fe77c5952665d0116f9eb843ce74e#diff-28aac9bc1c8569ab27000e85f746b3baR138

Let me know your thoughts.

**Comment by pippinsplugins** [comment]
Have you tested the change with the 404 plugin? I'm not sure that will work . . .

**Comment by JeroenSormani** [comment]
Haven't had the chance to test it yet, will try to do soon.

Should I just do a test order, and make sure /checkout isn't at the 404
logs of the plugin?
Thanks

On Mon, May 4, 2015 at 3:10 AM, Pippin Williamson <notifications@github.com>
wrote:

> Have you tested the change with the 404 plugin? I'm not sure that will
> work . . .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3366#issuecomment-98562888>
> .
>



-- 
Jeroen Sormani
http://www.jeroensormani.com
en
http://www.nederlandersfietsen.nl

**Comment by pippinsplugins** [comment]
It's the purchase confirmation page that gets redirected when that plugin
is active.

**Comment by JeroenSormani** [comment]
I just tried to test the 404 redirected plugin, but when disabling the hook, and try to get redirected by the plugin, it doesn't do that.

Does it need any specific settings? (the confirmation isn't captured either in the logs)

**Comment by pippinsplugins** [comment]
I don't believe it requires specific settings. I'll test it too to confirm everything is fine.

**Comment by pippinsplugins** [comment]
Still works fine.

**Pull request merged**
