### PR TITLE
Issue/3922

### PR DESCRIPTION
**Pull request by DevinWalker**
Resubmitting to `release/2.5` branch

### CODE REVIEW

**Comment by chriscct7** [comment]
This should have a nofollow noindex meta tag

**Comment by DevinWalker** [comment]
@chriscct7 that couldn't hurt! What about no-cache headers as described on #3922

**Comment by chriscct7** [comment]
Yeah I wouldn't mind those

**Comment by DevinWalker** [comment]
@chriscct7 added the no cache headers

**Pull request merged**
