### PR TITLE
Changing out credit card icons for new ones

### PR DESCRIPTION
**Pull request by lalunecreative**
New credit card icons. Tickets #4796 #4238 #2717

### CODE REVIEW

**Comment by lalunecreative** [comment]
I'm not sure what that iphone icon is for. I couldn't find where it's showing up in EDD anywhere, but if I need to update that one as well, let me know. It's also outdated.

**Comment by michaelbeil** [comment]
If you can update the iPhone icon as well, that would be great!

**Comment by lalunecreative** [comment]
iPhone icon. 
 #iphone

**Comment by michaelbeil** [comment]
That looks great! Want to add it to the PR?

**Comment by chriscct7** [comment]
While it's not in line with their logo design, I almost feel like we should increase the size of the "mastercard" text in the mastercard logo so it's readable. Anyone else have thoughts on that?

**Comment by lalunecreative** [comment]
Committed iphone icon. I could personally go either way with the mastercard text. It's going to be a tiny icon either way. Even with the new branding most of the tiny ones used for this only show the circle branding and not the text at all.

**Comment by michaelbeil** [comment]
I think it looks ok, but we could slightly increase the font size, though there is not much room for it as the icon is quite small indeed.

**Comment by michaelbeil** [comment]
The more I look at it, the more it seems to be spot on.

**Comment by pippinsplugins** [comment]
Manually merged!

**Pull request merged**
