### PR TITLE
Add Sanity Checks for some functions

### PR DESCRIPTION
**Pull request by dancameron**
Check to make sure the download_id passed to the bundled functions are actual downloads, otherwise a new download will be created/drafted if the id is not passed, invalid, or not a real download.

### CODE REVIEW

**Comment by cklosowski** [comment]
If it's not of the `download` post type we'll be ok as we have the checks here in the construct of the `EDD_Download` class:
```
		if( ! is_a( $download, 'WP_Post' ) ) {
			return false;
		}

		if( 'download' !== $download->post_type ) {
			return false;
		}
```

I could see changing it to making sure it's not empty so we're not creating drafts, but I think it'd be redundant to check it's post type twice.

Thoughts @pippinsplugins?

**Comment by dancameron** [comment]
Chris please refer to #3312 for the history. But....

I do get your point though and I agree these are a bit of bandaids to fix the issue that's arising (for me and others). 

Maybe we should talk about the conditional `false === $_id` in the __construct. I don't know why EDD should accept FALSE to create a drafted post. I had thought originally (because I skimmed the method) that a draft was created to prevent returning a FAIL instead of a graceful dummy object...now that I see FALSE being returned on a bunch of different conditions I don't understand the circumstances why a draft should ever be created.

Thanks!

**Comment by cklosowski** [comment]
I agree with you on the faults creating a new draft @dancameron. I've talked to Pippin about that and I'm hoping we can try and change that

**Comment by dancameron** [comment]
🍻




—
Dan Cameron
Sprout Venture Inc. & Sprout Apps

**Comment by pippinsplugins** [comment]
The post type checks should definitely stay within the `EDD_Download` class.

I'd like to go ahead and see `EDD_Download` get a `create()` method, just like we did with the `EDD_Customer` class.

**Comment by dancameron** [comment]
@pippinsplugins Thanks but for the sake of clarity does that mean a draft will not be created if "FALSE" is passed as the id? 

Cause the real issue isn't that the post_type checks are in the construct, it's that for some reason `false` is being passed and drafts are being created.
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/99f7940daa4d3e009e801bd1f20d7c4b9b3c7259/includes/class-edd-download.php#L140

**Comment by pippinsplugins** [comment]
Yes, drafts will not be created when passing `false` in.

**Comment by pippinsplugins** [comment]
At least that's my initial thought.

**Comment by dancameron** [comment]
Closing PR so that another could be used to address the direction discussed.

**Pull request closed without merging**
