### PR TITLE
#3873 - Fixes typo in includes/class-edd-stats.php#L91

### PR DESCRIPTION
**Pull request by christophherr**
Changed 'Last Quater' to 'Last Quarter'

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by christophherr** [comment]
You are welcome. I like to help where I can.
I found a few more typos. 
What is your preferred way to handle them? 
Should I open individual issues, create a "blanket issue" for all of them or just send PRs?

**Comment by pippinsplugins** [comment]
Log one issue for "Typos" and then open one or more PRs for it.

**Comment by christophherr** [comment]
Thanks.

**Pull request merged**
