### PR TITLE
Better Documentation

### PR DESCRIPTION
**Pull request by ahmadawais**
In accordance with [PHP Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/), this commit does the following

- Adds period at the end of single line comments, short/long descriptions (where needed)
- Adds short description for the `EDD()` function

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Thanks!

**Comment by ahmadawais** [comment]
😱Happy to help.

**Comment by ahmadawais** [comment]
@pippinsplugins May I ask what could be the reason of my name not showing up in the contributors list after the merger of this pull request?

**Comment by chriscct7** [comment]
Our contributors list is a list of the core team members, as that's how
WordPress.org uses that data

**Comment by ahmadawais** [comment]
@chriscct7 I was talking about this list at [GitHub](https://github.com/easydigitaldownloads/Easy-Digital-Downloads/graphs/contributors). What could be the possible reason?

**Comment by chriscct7** [comment]
Oh that list only lists the top 100 contributors, and in case of a tie
lists older contributors first.

**Comment by pippinsplugins** [comment]
@ahmadawais see https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/

**Comment by ahmadawais** [comment]
@chriscct7 and @pippinsplugins Thanks for the answers. I actually didn't know that. I thought I had committed to the wrong branch or something. That's why I was trying to understand what could have went wrong. 

Thanks for the help :)

**Pull request merged**
