### PR TITLE
Move Download CPT icon to registration arguments

### PR DESCRIPTION
**Pull request by nosegraze**
I think this is better because then it's easier and more intuitive to change the menu icon.

And should #3052 be revisited? It seems like the effort to move to SVG has been basically dead for over a year unless there's more discussion I haven't found.

### CODE REVIEW

**Comment by michaelbeil** [comment]
Could you share a screenshot of the changes you are proposing?

**Comment by nosegraze** [comment]
Well visually it wouldn't look any different so I'm not sure what you want me to screenshot.

Basically right now the admin menu icon (the download icon) is being added via CSS in the header. This makes it kind of a pain to change. I'm suggesting removing that CSS and utilizing the `menu_item` argument in the post type registration instead: https://codex.wordpress.org/Function_Reference/register_post_type#menu_icon Putting the dashicon name there allows it to be changed via the CTP arguments filter.

**Comment by michaelbeil** [comment]
This would be a good addition. Gonna make an issue for it so we can track it accordingly.

**Comment by michaelbeil** [comment]
Regarding the SVG issue, why don't you bring that question up in that issue?

**Comment by nosegraze** [comment]
Will do!

**Comment by cklosowski** [comment]
Lining issue with PR #5033

**Pull request merged**
