### PR TITLE
Make state field select instead of text if possible

### PR DESCRIPTION
**Pull request by cklosowski**
Replaces #4014 for #4013

### CODE REVIEW

**Comment by cklosowski** [comment]
@SDavisMedia @brashrebel mind testing out this PR for me?

**Comment by cklosowski** [comment]
You can use branch `brashrebel-issue/4013`

**Comment by brashrebel** [comment]
Just tested and it works for me. Although it seems that this was already working on the checkout screen in `release/2.6`

**Comment by cklosowski** [comment]
Yes, it was working on checkout, but I changed where the JS lives, so it's
best to test them both to make sure I didn't break the existing
functionality.

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by cklosowski** [comment]
Actually I think there's a problem here when we have AJAX disabled. Previously all the JS to do this was in the `edd-checkout-global.js` which is loaded even if the AJAX is disabled. With the functions to do this existing in the `edd-ajax.js` file, if AJAX is disabled, then these will never load for the checkout.

We'll need to fix that.

**Pull request merged**
