### PR TITLE
Add the edd prefix to the ui-tooltip class ...

### PR DESCRIPTION
**Pull request by michaelbeil**
...  selector.

#4641

### CODE REVIEW

**Comment by pippinsplugins** [comment]
This will also need to adjust the classes on the tool tip spans, otherwise it breaks the CSS>

**Comment by michaelbeil** [comment]
I do not see any tooltip spans on release/2.6 within our screens. Am I missing something?

**Comment by pippinsplugins** [comment]
I believe that class gets added automatically. All we do in the HTML to set them up is this:
```
<span alt="f223" class="edd-help-tip dashicons dashicons-editor-help">content here</span>
```

**Comment by michaelbeil** [comment]
I only see the edd-help-tip class being added here: 
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.6/includes/admin/payments/view-order-details.php#L81 https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.6/includes/admin/payments/view-order-details.php#L180  
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/2.6/includes/admin/payments/view-order-details.php#L237

**Comment by cklosowski** [comment]
@m @pippinsplugins test that out, there is a `jquery ui tooltip` option to define a class for the hover state.

**Comment by michaelbeil** [comment]
This works well.

**Pull request merged**
