### PR TITLE
Let edd_get_payment_status() take a payment ID

### PR DESCRIPTION
**Pull request by ghost1227**

### CODE REVIEW

**Comment by ghost1227** [comment]
Fixes #4041

**Comment by pippinsplugins** [comment]
Looks good. Could you add some unit tests too?

**Comment by ghost1227** [comment]
Yep!

**Comment by cklosowski** [comment]
I want to hold off on merging this until we get `release/2.5` merged into master, then have this use `new EDD_Payment()` instead of `get_post`. Other than that, the logic is sound.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Closing in favor of https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4537

**Pull request closed without merging**
