### PR TITLE
Disable xdebug (for non-HHVM builds) to speed up tests

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Related: https://github.com/pods-framework/pods/issues/3283

Extra props to @pglewis for finding the issue and helping us fix it in Pods :)

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Previous elapsed time: ~15 minutes
New elapsed time w/o xdebug: ~4 minutes

Previous total time: ~45 minutes
New total time w/o xdebug: ~15 minutes

**Comment by sc0ttkclark** [comment]
@pippinsplugins consider this your xmas/kwanza/hanukkah gift from the Pods team :)

**Comment by pippinsplugins** [comment]
So awesome!

**Comment by sc0ttkclark** [comment]
Party on Wayne! :)

**Comment by cklosowski** [comment]
🎸🎸🎸

**Pull request merged**
