### PR TITLE
Display Buy Now text on buy now buttons

### PR DESCRIPTION
**Pull request by ghost1227**
Issue #3204, resubmit for release/2.4

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Thanks @ghost1227 !

**Comment by cklosowski** [comment]
With 2.3 going out, can you refresh the branch from `release/2.4`

**Comment by cklosowski** [comment]
@ghost1227 Can you refresh your branch with `release/2.4` so this will merge cleanly?

**Comment by pippinsplugins** [comment]
@ghost1227 Could you refresh this please?

**Pull request closed without merging**
