### PR TITLE
Provide $price to callback functions

### PR DESCRIPTION
**Pull request by ericnicolaas**
It can be helpful to pass `$price` to the `edd_purchase_link_args` filter, particularly since the price is used to modify the button text in certain cases. This adds it as an optional second argument to the callback functions. 

It also cleans up the conditional check on line 127 since `$price` is always defined; it just needs to check that it isn't `false`.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Price is included inside of args. Why not just access it there?

**Comment by ericnicolaas** [comment]
The price in args is used to determine whether to show the price; it doesn't store the price. `$price` on the other hand is the calculated price for the product. Note below the var_dump output of `$args` and `$price`: 
screen shot 2015-05-22 at 11 16 10 am

**Comment by cklosowski** [comment]
Yeah the actual price isn't passed in `$args`. I'm trying to see if there's a better solution to including this in the `$args`. Problem is we'd have to name it something other than `price` since that's used as a `bool` of it to show the price.

Once we have a price could we send it as maybe `$args['display_price']`?

**Comment by pippinsplugins** [comment]
I'm :+1: for `display_price`

**Comment by pippinsplugins** [comment]
@cklosowski @ericnicolaas thoughts on `display_price`?

**Comment by ericnicolaas** [comment]
@pippinsplugins @cklosowski `display_price` sounds good to me. I'll work on an update to the PR.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by ericnicolaas** [comment]
Looks like somehow I've managed to add a whole stack of other commits into this PR. Happy to just start with a fresh PR if you'd prefer. Otherwise it looks like it's mostly your stuff anyway, @pippinsplugins

**Comment by cklosowski** [comment]
@ericnicolaas yeah if you could just resubmit it. I'd appreciate it, will keep the merge history cleaner. I'll get an issue written up so we can track it as well.

**Comment by cklosowski** [comment]
New issue created in #3849. If you could submit a new PR against `release/2.5` that'd be prefect. I'll slate the issue to be fixed there.

**Pull request closed without merging**
