### PR TITLE
Move API to wp action

### PR DESCRIPTION
**Pull request by ghost1227**
...it works!!!

Issue #3410

### CODE REVIEW

**Comment by pippinsplugins** [comment]
We'll have to test this much more extensively but that's great to hear that it appears to work at least :)

**Comment by ghost1227** [comment]
I've got half an hour of running through all the endpoints... nothing missing that I can see!

**Comment by pippinsplugins** [comment]
@ghost1227 could you bring this branch up to date so it merges cleanly?

**Comment by pippinsplugins** [comment]
@ghost1227 resubmit to `issue/3410`

**Comment by ghost1227** [comment]
@pippin done

**Pull request closed without merging**
