### PR TITLE
Add our submenu item to the Dashboard menu list #8898

### LINKED ISSUE #8898: Add reports menu entry in top level Dashboard menu.
### Explain your enhancement (please be detailed)
Add a link to the EDD Reports view to the main Dashboard menu items.

### Justification or use case
To help us encourage store owners to see the performance of their store, we can expose them to the reports menu easier.

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #8898 

Proposed Changes:
1. Adds a 'Reports' menu item under the main Dashboard widget, which links to the EDD Reports view.

### CODE REVIEW

**Comment by cklosowski** [comment]
I attempted to do this with `add_dashboard_page`, however that generates a URL that is for `index.php` which our reports are not registered for. Our reports are registered for `edit.php`.

**Comment by cklosowski** [comment]
image

**Review by ashleyfae — COMMENTED** [review]
I'm personally not a fan of this change. It feels like we're starting to put our stuff where it doesn't quite belong.

Cod works fine though.

At the very least, should we change the `Reports` label? Because we're infringing on space that isn't ours, it's not clear what these reports are for. People could have reports for all kinds of stuff: site traffic, affiliates, etc. Do we need an `EDD` prefix?

**Comment by cklosowski** [comment]
@ashleyfae we could do something like `Store Reports` or `Shop Reports`?

`EDD Reports` is also an option, I think a more generic naming convention there is better (so long as it isn't too generic, as you've pointed out).

**Comment by ashleyfae** [comment]
EDD 3.0 uses `Store` in various places, so maybe we should stick with that. I imagine the only conflict there would be if someone is using more than one shop plugin (like EDD + Woo). Which, I'm sure happens, but is minimal.

**Review by ashleyfae — APPROVED** [review]

**Review by robincornett — APPROVED** [review]
I agree that the label needs to be more specific than just "Reports"; adding "Store" works for me.

**Pull request merged**
