### PR TITLE
Fix (sub)total amount attributes

### PR DESCRIPTION
**Pull request by JeroenSormani**
Splitted PR from https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3693

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@JeroenSormani why is the subtotal incorrect?

**Comment by JeroenSormani** [comment]
@pippinsplugins 
The attribute says `data-total` while the function used is `edd_get_cart_subtotal()`.
There's also a attribute `data-subtotal` which also has the `edd_get_cart_subtotal()` function (this one is correct).

Vice versa for the other file.

**Comment by pippinsplugins** [comment]
Huh, that's "great".

Let's definitely get that confusion fixed. I'm not going to merge this yet as we need to be super careful with it, but I'm going to milestone it for 2.6.

**Comment by JeroenSormani** [comment]
Cool. I think I did check when I made those changes, and I couldn't find those attributes used in EDD Core.

**Comment by cklosowski** [comment]
Going to fix up the merge conflicts and get this directly into our `release/2.6` branch. Using #4697 instead keeps commit history in place.

**Pull request closed without merging**
