### PR TITLE
Do not hide repeatable row remove link

### LINKED ISSUE #8192: 3.0 - Impossible to "clear" a repeatable row when there is only one
### Expected behavior
I expect to be able to remove a repeatable row, even if it is the only row (in 2.9, clicking "Remove" clears the contents of the first row).

### Actual behavior
In 3.0, due to CSS hiding the "Remove" link when there is only one row, it is not possible to clear the data out of a repeatable row with one click if there is only one row ([CSS added in commit c30cc01](https://github.com/easydigitaldownloads/easy-digital-downloads/commit/c30cc01ef071a589cfb45140e9682127baad825c)).

### Steps to reproduce the behavior
1) Create/edit a download in 3.0.
2) Scroll to the Download Files metabox and add a file.
3) Click "Add New File". Note that both rows show a "Remove" link.
4) Remove one of the rows. The "Remove" link no longer shows.

### Information (if a specific version is affected):
PHP Version: 7.4.1
EDD Version (or branch): release/3.0
WordPress Version: 5.5.3

Any other relevant information:
In some cases, it's possible to manually clear out a row, but for an extension like Software Licensing, it is currently not possible to clear out the download once it has been selected (which is a separate issue).

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #8192

### CODE REVIEW

**Comment by LisaCee** [comment]
If there are multiple rows, this removes the row as expected.

There is different behavior between the remove on Download Files and License Upgrade Paths, though.  If there is only one row in Download Files and you click remove, it clears the data.  In the same scenario in License Upgrade Paths, the Download select and Prorate check don't get cleared.  Price Option and Discount are both cleared.

**Comment by robincornett** [comment]
The download select is because of #8193. I'll have to look into the JavaScript to see why the checkbox isn't clearing--my initial scan suggests that the script is resetting `input` and `select` but not anything else, which would explain why, but I need to see tomorrow if that is the case.

**Comment by robincornett** [comment]
Update: the checkbox not clearing also happens in 2.9; I think the script does just clear out `input` and `select` elements and ignores checkboxes.

@ashleyfae is that something we would want to change?

**Comment by ashleyfae** [comment]
> Update: the checkbox not clearing also happens in 2.9; I think the script does just clear out `input` and `select` elements and ignores checkboxes.
> 
> @ashleyfae is that something we would want to change?

@robincornett I'm fine with leaving it as-is for now.

**Review by ashleyfae — APPROVED** [review]

**Review by LisaCee — APPROVED** [review]

**Comment by ashleyfae** [comment]
@robincornett Can you sort out the conflicts? Then we can get this merged!

**Comment by ashleyfae** [comment]
Sorry @robincornett -- there are merge conflicts again. :laughing:

**Pull request merged**
