### PR TITLE
3.0 - Optimize Report Chart Tooltip Axis Formatting

### LINKED ISSUE #7908: 3.0 - Reports - Graph tick labels are misleading when showing month-by-month view
### Expected behavior

When I hover over a point on the graph, I expect the label to tell me exactly which period this covers.

### Actual behavior

When you're viewing a date range that shows data grouped by month ("This Year" and "Last Year" ranges do this), the ticks are formatted like this:

`July 1, 2019`

However, the data is actually covering the _full month_ of July -- not just the 1st. So the tick should be `July 2019`

### Steps to reproduce the behavior
1) Go to Downloads > Reports.
2) Set the date range to This Year or Last Year.
3) Hover over a point on the graph.

### Information (if a specific version is affected):
PHP Version:

EDD Version (or branch): release/3.0

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by spencerfinnell**
Fixes #7908 

Proposed Changes:
1. Adjust axis and tooltip formats based on current date range.
2. Use UTC offset when formatting tooltips on smaller ranges.
3. Use UTC when showing averages for larger date ranges.
4. Only show timezone when date filter is appropriate.

### CODE REVIEW

**Comment by cklosowski** [comment]
@spencerfinnell this has broken every unit test, can we isolate what modified all the report date dropdowns?

**Comment by spencerfinnell** [comment]
@cklosowski I moved them out in https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7930/commits/94f9a74413565b2d67efc62527552b9a357e0fa4 because showing a timezone for daily, monthly, or yearly averages aren't relevant. I'll update the tests.

**Comment by LisaCee** [comment]
It looks good, but I'm getting some weird data - possibly from testing #7910.  

I have 8 sales for May, but the tooltip only shows 2.  Is that expected behavior?

**Comment by spencerfinnell** [comment]
@LisaCee On all date ranges? I just merged some of @robincornett's changes that might help. You can also test your data against https://github.com/easydigitaldownloads/easy-digital-downloads/pull/7934

**Comment by LisaCee** [comment]
A fresh pull made the difference.  This UI looks so much better!  Great job.

**Pull request merged**
