### PR TITLE
Better Documentation and File Long Description

### PR DESCRIPTION
**Pull request by ahmadawais**
This commit adds
- Better docs
- Long desc in the file header

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Thanks for this @ahmadawais.

Note, in the future we would prefer that these kind of changes get submitted as a single PR across all files (or at least all files in a category) instead of a PR for each little piece.

**Comment by ahmadawais** [comment]
@pippinsplugins 
I planned to go file by file. Can you tell me what did you mean by all files in a category?

**Comment by pippinsplugins** [comment]
File by file is fine :)

By category I mean, for example, all files inside of `includes/payments/`

**Comment by ahmadawais** [comment]
@pippinsplugins Got it :) I'll keep up with file by file or category by category.

**Pull request merged**
