### PR TITLE
Add admin page helper function for extension developers (Solves #2657)

### PR DESCRIPTION
**Pull request by chriscct7**
Implements `edd_is_admin` as defined in #2657

### CODE REVIEW

**Comment by chriscct7** [comment]
Whenever #3060 is merged, @cklosowski will need to add a switch in this function for the customers page as well as add detection for that page to `edd_is_admin_page`

**Comment by pippinsplugins** [comment]
@chriscct7 Always include a commit message, not just the issue number. With just the issue number, clicking on the commit just takes you to the issue, not the commit. Also it doesn't mean anything,

**Comment by chriscct7** [comment]
@cklosowski now that customer UI is merged, when you have the issues ironed out with that I can add items for this.

**Comment by chriscct7** [comment]
Resubmitted against release/2.3 as #3109

**Pull request closed without merging**
