### PR TITLE
.htaccess added filter for file formats

### PR DESCRIPTION
**Pull request by somewebmedia**
Video file formats should be allowed as well, in case a theme needs those files for showcase

### CODE REVIEW

**Comment by chriscct7** [comment]
Strongly against this PR on the basis that many people have uploaded full videos that they sell via EDD that they are expecting to be protected. This would open those files to be directly hotlinked. If anything, I'm for removing all of the exceptions and then use a bulk upgrade routine to move a copy of previously whitelisted ones to the main uploads folder, and then stop whitelisting any extensions

**Comment by somewebmedia** [comment]
@chriscct7 Ok, I've removed video types, but there should be some filter for the people who want better control of this, so my proposal is 'edd_protected_directory_allowed_filetypes' filter.

**Comment by somewebmedia** [comment]
In that case even .mp3 and .ogg should be removed from the default list.

**Comment by chriscct7** [comment]
Whatever was already allowed should remain allowed for now. We'll consider removing those exceptions on a different issue.

**Comment by somewebmedia** [comment]
@chriscct7 Done. And please consider this filter for filetypes, I encountered a need for video files to be visible as a showcase, but there is no easy workaround.

**Comment by chriscct7** [comment]
Looks good

**Comment by pippinsplugins** [comment]
I like the idea of a filter here.

If @cklosowski agrees as well, we'll merge.

**Comment by cklosowski** [comment]
Filter here is a fantastic idea. It cant hurt and offers people to make changes they deem necessary for their own sites. big :+1: from me.

**Comment by pippinsplugins** [comment]
Thanks @somewebmedia !

**Pull request merged**
