### PR TITLE
Pull payment IDs from customer table for edd_get_users_purchases()

### PR DESCRIPTION
**Pull request by pippinsplugins**
#3031

### CODE REVIEW

**Comment by cklosowski** [comment]
If we hold off on this, we can use ```new EDD_Customer( $_id_or_email )``` to pull these.

**Comment by pippinsplugins** [comment]
Smart :+1:

**Comment by pippinsplugins** [comment]
This will fail if you pass a user ID. `edd_get_users_purchases()` is designed to take a user ID, not a customer ID.

**Comment by cklosowski** [comment]
Ah, yes @pippinsplugins I'll change it to the get_by method in `EDD_DB_Customers`. We should come up with a way to instantiate `EDD_Customer` via the User ID...but there's just not a good way.

We could add a parameter to the `__construct` of `EDD_Customer` that flags the input as a `user_id` which can default to false. So if you say:
`EDD_Customer( $user_id, true )` it'll do the lookup by the `user_id`column. Otherwise by `email` or `customer_id`

**Comment by pippinsplugins** [comment]
I like the idea of a `$by_user_id = false` parameter.

**Pull request merged**
