### PR TITLE
add filter for edd_cart_item_price()

### PR DESCRIPTION
**Pull request by JeroenSormani**
Hey guys,

Just a small PR to add a filter to the checkout price label.

Cheers!

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Looks good to me! I Both @cklosowski and I feel like there may already be a way to do this, so we're going to do some digging before merging. Assuming we don't find a way, we'll merge it in.

Second note: since this against `master`, please do not merge until 2.3 is ready to be merged into `master.

**Comment by JeroenSormani** [comment]
There is a filter here to filter the cart item price; https://github.com/JeroenSormani/Easy-Digital-Downloads/blob/new-filter/includes/cart/functions.php#L447

But that doesn't allow to change the complete cart price label.

This where I use the filter for, it is not possible without; http://cl.ly/image/1O0R0c3h1I1n
(free 'EDD Sale Price' plugin)

**Comment by pippinsplugins** [comment]
Ah! Excellent example. Ok merging.

**Comment by pippinsplugins** [comment]
Well merging once 2.3 is ready to go into `master`.

**Comment by cklosowski** [comment]
:+1: Thanks @JeroenSormani :)

**Pull request merged**
