### PR TITLE
Switch 3.0 branch to use BuildKite

### PR DESCRIPTION
**Pull request by cklosowski**
This PR serves to separate us from Travis-CI and start using Buildkite for our unit test automation.

Right now it doesn't run a matrix build of PHP/WP versions but we are looking into that. The build is setup to run PHP 7.3 and WordPress 5.5.3. This can be changed via Environment Variables `WP_VERSION` and `PHP_VERSION` but is coded into the `docker-compose.yml` file.

### CODE REVIEW

**Review by ashleyfae — APPROVED** [review]
I'm unable to run this locally because I'm already using port 80 :sweat_smile: But I can see that it works!

**Comment by cklosowski** [comment]
@ashleyfae I've updated the PR to include the matrix system:
https://buildkite.com/sandhills-development-llc/easy-digital-downloads/builds/104

I've disabled the GitHub integration while I was testing things out and until we merge and get this into the main branch. Once approved I'll turn on the github integration to listen for PRs

**Review by ashleyfae — CHANGES_REQUESTED** [review]
The `run-tests-local.sh` file is accidentally the same as the internal copy.

https://github.com/easydigitaldownloads/easy-digital-downloads/blob/f3e3cfd57769e8d013220a70ed52abac66485c43/bin/run-tests-local.sh

**Comment by cklosowski** [comment]
@ashleyfae I think that should do it!

**Review by ashleyfae — APPROVED** [review]
Works now :raised_hands:

**Pull request merged**
