### PR TITLE
Split EDD menu into Store and Downloads menu items

### PR DESCRIPTION
**Pull request by ghost1227**
Issue #2880

### CODE REVIEW

**Comment by danieliser** [comment]
Just a thought.

You could even go as far as to make a 3rd Top level menu item for extensions to use that only shows if an extension has added a menu item to it.

You would end up with

Store
Downloads
Extra Settings / Store Extensions

This further extrapolates them. If they don't really have a place semantically in Store or Downloads they can easily fit into menu 3 which is basically misc settings. Social Login & Wishlists for example.

**Comment by ghost1227** [comment]
I don't really think that's necessary. Conceptually it's not a horrible idea, but I think it'll be more complicated than it's worth given the few extensions that actually need to provide a dedicated menu item. Plus, the few that DO provide a dedicated menu item are already registering their own.

**Comment by danieliser** [comment]
I see your point, but It's more about the future growth of EDD in my opinion. What may not exist now could easily be there tomorow with the growth rate of EDD extensions. That said for me its more semantics & organization. I hate cluttered menus, and some things just don't feel like they belong under either of those menus.

As for existing extensions, they will all hook the 'downloads' menu anyways and will require modification to move them to 'Store' menu any ways, giving them a 3rd option now means less maintanance in the future.

As I said this is purely based on my opinion, and the fact that EDD is growing rapidly.

**Comment by pippinsplugins** [comment]
It's definitely something to consider.

**Comment by cklosowski** [comment]
@ghost1227 If you could please bring the unit tests up to speed so they are passing, not sure why so many are failing here...have you merged ```release/2.3``` in recently?

Also, can we clean up the spacing on this list:
screen shot 2015-02-11 at 5 39 19 pm

Assignments like this should be aligned with spaces, no tabs at all (based on WP Coding standards)
I know this existed prior to your updates, but let's just clean it up while we're here.

**Comment by ghost1227** [comment]
no problem

**Comment by ghost1227** [comment]
@cklosowski Fixed the indentation issues... Not sure what you mean by things failing though, it's showing 100% passing as far as I can see...

**Comment by cklosowski** [comment]
Yep initial commits were failing for some reason. Will test this.

**Comment by ghost1227** [comment]
Roger that!

**Comment by pippinsplugins** [comment]
I'm going to close this PR for now. We need to decide exactly how we're splitting this up before we do too much with actual changes.

**Pull request closed without merging**
