### PR TITLE
Adds a button to reports to clear reports transient cache issue/3812

### LINKED ISSUE #3812: Admin Feature: Refresh reports button
Report data is stored in transients. If a user has a busy site, it's helpful that they have a way to refresh reports and clear the transient cache. How about a button like this?

refresh-button

and once the cache is cleared:

9-17-2015 4-06-30 pm

This can be achieved with code like this:

```
/**
 * EDD Reports Refresh Button
 * @description: Outputs a "Refresh Reports" button for graphs
 */
function edd_reports_refresh_button() {

    $url = wp_nonce_url( add_query_arg( array(
        'edd_action'  => 'refresh_reports_transients',
        'edd-message' => 'refreshed-reports'
    ) ), 'edd-refresh-reports' );

    echo '<a href="' . $url . '" data-tooltip="' . __( 'Clicking this will clear the reports cache.', 'edd' ) . '" data-tooltip-my-position="right center"  data-tooltip-target-position="left center" class="button alignright edd-refresh-reports-button edd-tooltip">' . __( 'Refresh Reports', 'edd' ) . '</a>';

}

add_action( 'edd_reports_graph_additional_stats', 'edd_reports_refresh_button' );

/**
 * Trigger the refresh of reports transients
 *
 * @since 1.3
 *
 * @param array $data Parameters sent from Settings page
 *
 * @return void
 */
function edd_run_refresh_reports_transients( $data ) {

    if ( ! wp_verify_nonce( $data['_wpnonce'], 'edd-refresh-reports' ) ) {
        return;
    }

    //Delete transients
    delete_transient( 'edd_estimated_monthly_stats' );
    delete_transient( 'edd_earnings_total' );
    delete_transient( md5( 'edd_earnings_this_monththis_month' ) );
    delete_transient( md5( 'edd_earnings_todaytoday' ) );

}

add_action( 'edd_refresh_reports_transients', 'edd_run_refresh_reports_transients' );
```

...Then change this here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/payments/functions.php#L689

to:

```
    if ( ! empty( $_GET['_wpnonce'] ) && wp_verify_nonce( $_GET['_wpnonce'], 'edd-refresh-reports' ) ) {
        $earnings = false;
    } else {
        $earnings = get_transient( $key );
    }
```

I have it working in this branch on Give: https://github.com/WordImpress/Give/tree/issue/210

The issue stems from complaints like this: https://github.com/WordImpress/Give/issues/85

LMK if you'd be interested in this functionality with in EDD and I can submit a PR :smile:

### PR DESCRIPTION
**Pull request by DevinWalker**
Fixes #3812

### CODE REVIEW

**Comment by DevinWalker** [comment]
Note: I didn't add any tooltip functionality. Give uses qtip2 for tooltips throughout so I swapped out that for a standard title tag on the button.

**Comment by pippinsplugins** [comment]
@DevinWalker looks good! Since it's done, we can put this in sooner. How about 2.5? @cklosowski ?

**Comment by mindctrl** [comment]
I'd like to make the language less technical here.

Specifically:
- Change "The reports cache has been cleared."  to "The reports have been refreshed."
- Change "Clicking this will clear the reports cache" to "Clicking this will refresh the reports"

Or something like that. Thoughts?

**Comment by cklosowski** [comment]
I'm with @mindctrl here, let's bring the language to a user level, they don't need to know caching or anything. I think 'Refresh' is word enough.

@DevinWalker It also needs to be updated to accommodate for this change, which adds prefixes to all our stats transients:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3830#event-419204021

**Comment by DevinWalker** [comment]
@mindctrl @cklosowski sounds good to me!

**Comment by DevinWalker** [comment]
I have updated the language as suggested by @mindctrl 

9-29-2015 12-58-29 pm

**Comment by DevinWalker** [comment]
@cklosowski regarding https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3830#event-419204021 - should the `edd_stats_*` transients be cleared also here: https://github.com/DevinWalker/Easy-Digital-Downloads/blob/master/includes/admin/reporting/graphing.php#L803  

I was testing and it seemed working properly without clearing those? I wasn't testing with taxes though... would love to hear your insight.

**Comment by michaelbeil** [comment]
It looks like the hover title on the `Refresh Reports` button is still `Clicking this will clear the reports cache`, instead of `Clicking this will refresh the reports`.

**Comment by cklosowski** [comment]
Going to get this fixed up from merge conflicts, and open a new pr under branch `issue/3812`

**Pull request closed without merging**
