### PR TITLE
Improve category and tag taxonomy labels. #4232.

### PR DESCRIPTION
**Pull request by mindctrl**
#4232

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@mindctrl Looks like this has broken the build. Think you could update the failing tests to match these changes?

**Comment by mindctrl** [comment]
@pippinsplugins :+1:  I'll look at those tonight or in the morning.

**Comment by mindctrl** [comment]
@pippinsplugins updated unit tests. All passing except WP 4.4.2, which appears to not be available yet.

**Comment by pippinsplugins** [comment]
Looks good to me.

@cklosowski Merge if you agree.

**Comment by michaelbeil** [comment]
Odd that the builds are not finding that dir since the 4.4.2 dir is available here https://develop.svn.wordpress.org/tags/4.4.2/tests/phpunit/includes/.

**Comment by cklosowski** [comment]
👍

**Pull request merged**
