### PR TITLE
Given our themes are now free and the code doesn't work on bundles

### PR DESCRIPTION
**Pull request by chriscct7**
Remove the confusing wording

### CODE REVIEW

**Comment by cklosowski** [comment]
I agree that `themes` needs to be removed, but I think the `non-bundle` part get's a little wordy for people.

`extension purchases` would be just as accurate (since bundles aren't extensions)

We should also add GA tracking on that extensions link:
`https://easydigitaldownloads.com/extensions?utm_source=notice&utm_medium=admin&utm_content=extensions&utm_campaign=edd-tracking`

**Comment by pippinsplugins** [comment]
I'd agree with changing it to just `extension1

**Comment by cklosowski** [comment]
@pippinsplugins I talked with @chriscct7 and I do think maybe we can word this better to reduce confusion, but I don't want to make any large changes without having a baseline on the current wording.

**Comment by pippinsplugins** [comment]
I vote we don't change it actually, for a couple of reasons:

1. There's nothing to say we won't have paid themes in the future
2. All translations would need to be updated

Does anyone know if there is evidence (such as a support ticket) of someone being confused why they couldn't apply the discount to a theme?

**Comment by chriscct7** [comment]
I had a couple people open support tickets on this, which is why I actually opened the ticket. I'll see if I can dig them out of you want. They were mostly people who thought the code would work for marketify and such since they're paid but link off the main site. But I think the better thing might be to clarify "sold on our site" on the end of that sentence

**Comment by pippinsplugins** [comment]
@chriscct7 Do you remember if they were confused because the themes were free or they were confused because they couldn't use the code on a bundle?

**Comment by chriscct7** [comment]
Its not that they were confused with our themes, what happened was people were seeing 20% off themes, they'd click on the link to go to our site and on our site we list Marketify (for example) which is not free and they were going to ThemeForest from our site and trying to apply the coupon. And obviously we get the bundles issue every week as well. Adding `sold on our site (excludes bundles)` would solve all of these tickets we frequently get

**Comment by pippinsplugins** [comment]
It doesn't exclude all bundles (gateway bundles not excluded).

I'm re-considering my objection from earlier.

**Comment by chriscct7** [comment]
Oh really? I've always thought all bundles were excluded

**Comment by pippinsplugins** [comment]
Nope, just Core and Marketplace.

**Pull request closed without merging**
