### PR TITLE
Add cart key to  edd_checkout_cart_item_title_after action 

### PR DESCRIPTION
**Pull request by Shelob9**
#4685

### CODE REVIEW

**Comment by Shelob9** [comment]
BTW to see my use case, add an item, not a bundle to the cart on our site.

**Comment by cklosowski** [comment]
Looks good to me @pippinsplugins

**Comment by cklosowski** [comment]
Closing this one to merge in with #4687 for the `release/2.6` branch.

**Comment by cklosowski** [comment]
@Shelob9 your commit history is in tact.

**Pull request closed without merging**
