### PR TITLE
Ensure user has install_plugins capability to install Jilt #8115

### LINKED ISSUE #8115: Allow Jilt installation to super admins only when in MU
### Explain your enhancement (please be detailed)
This was reported by a customer what he considers a security issue. He is using EDD in a MU setup and admins can install Jilt by just clicking the button available on the EDD Emails page.
He does not use Jilt and does not want it to be available to admins.

### Justification or use case
Customer does not use Jilt and does not want it to be available to admins on his network sites.

### PR DESCRIPTION
**Pull request by ashleyfae**
Fixes #8115

Proposed Changes:
1. Add additional check for `install_plugins` capability.

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
This works to hide the Jilt button, but it feels a little off to show the setting/description if there isn't anything a user can do (other than click the links).

**Comment by ashleyfae** [comment]
> This works to hide the Jilt button, but it feels a little off to show the setting/description if there isn't anything a user can do (other than click the links).

I'm kind of in two minds about that. On the one hand, it's nice to say, _"this option exists"_ because then the user can ask the network admin about it. On the other hand I do agree it's a little weird. We could have some other kind of notice like, _"Ask the network admin to install this for you"_ but I can't think of good wording right now.

**Comment by robincornett** [comment]
Yes, I agree--everything I can think of wording wise feels a little smarmy. It's a little complicated by the description being separated from the buttons.

The PR does address and resolve the immediate issue. I'm happy to approve and if we run into confusion later then we could look into updating the language. It may not be necessary.

**Review by robincornett — APPROVED** [review]

**Comment by cklosowski** [comment]
I restarted the failed builds on Travis. All is good now.

**Pull request merged**
