### PR TITLE
Unserialize extra payment meta

### LINKED ISSUE #7221: 3.0 Arrays in payment meta become strings after migration
### Expected behavior
After migrating, I expect all values to remain in the same format. 

### Actual behavior
Payment meta (maybe other data as well) wraps serialized arrays as a string during migration. For example:

Value in DB before migration:
`a:1:{s:7:"52622-1";b:1;}`

Value in DB after migration:
`s:24:"a:1:{s:7:"52622-1";b:1;}";`

### Steps to reproduce the behavior
1) Have some payment meta
2) Migrate to EDD3

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

### PR DESCRIPTION
**Pull request by mintplugins**
Fixes #7221

### CODE REVIEW

**Comment by cklosowski** [comment]
@JJJ I don't believe so. This appears to be additional 3rd party meta stored in that master-meta key of `_edd_payment_meta` that plenty of extensions injected data into.

**Comment by mintplugins** [comment]
I wonder if anyone ever added custom meta to a discount. Should we migrate all meta attached to a discount post type just to be safe?

**Comment by cklosowski** [comment]
We already are migrating discount meta: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L179

**Comment by mintplugins** [comment]
Ah right. I think we do have to run maybe_unserialize on that though, unless I'm reading it wrong.

**Comment by mintplugins** [comment]
I might have been reading it wrong. I believe that happens here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L160

**Comment by cklosowski** [comment]
I think it's unlikely as we run it up here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/admin/upgrades/v3/class-data-migrator.php#L160

The main reason this happened with the `_edd_payment_meta` is because it
was a dumping ground for data.

**Pull request merged**
