### PR TITLE
Add bulk updated messages

### LINKED ISSUE #2941: Bulk edit notifications are wrong
Currently, we're not updating the bulk edit notifications the way we do for the traditional notifications. As such, when downloads are bulk edited, the notice says 'post updated' instead of 'download updated'. Submitting my patch shortly...

screen shot 2015-01-07 at 3 33 31 pm

### PR DESCRIPTION
**Pull request by ghost1227**
Fixes #2941

### CODE REVIEW

**Comment by pippinsplugins** [comment]
I forgot those even existed.

**Comment by ghost1227** [comment]
I didn't!

**Comment by ghost1227** [comment]
Even wrote the unit test... that's a first!

**Comment by pippinsplugins** [comment]
:)

**Pull request merged**
