### PR TITLE
Adds "sections" to settings tabs

### PR DESCRIPTION
**Pull request by benjaminprojas**
This feature allows plugins (as well as EDD) to create separate sections under the settings tabs addressing this issue: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/1960

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@benjaminprojas This is causing some undefined indexes: https://travis-ci.org/easydigitaldownloads/Easy-Digital-Downloads/jobs/65249570

Could you resolve those?

**Comment by benjaminprojas** [comment]
@pippinsplugins should be fixed now.

**Comment by pippinsplugins** [comment]
@benjaminprojas Are you able to bring this up to date with `release/2.5` so it merges cleanly?

**Comment by benjaminprojas** [comment]
@pippinsplugins what is the ETA for release/2.5? I just left for vacation but can work on getting it updated if necessary.

**Comment by pippinsplugins** [comment]
@benjaminprojas end of the month.

If we can't get it in for 2.5, best thing would be to submit to `issue/1960` so that we can get it in there and then merge into release branch at anytime.

**Comment by benjaminprojas** [comment]
@pippinsplugins sorry about the delay in getting back.  I was on vacation until just this week.  I will work on getting this updated and merged in within the next few days.

**Comment by benjaminprojas** [comment]
@pippinsplugins my fork was way messed up, creating a new PR here: https://github.com/easydigitaldownloads/Easy-Digital-Downloads/pull/3829

**Pull request closed without merging**
