### PR TITLE
Remove the main section if there are no settings registered and default

### PR DESCRIPTION
**Pull request by cklosowski**
...to the first non-empty section #4211

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@mindctrl could you give this a test?

**Comment by mindctrl** [comment]
@pippinsplugins @cklosowski this causes extensions that don't support subsections yet to not show at all. In the screenshot below, Mailchimp 2.5.5 (pre-subsections version) is activated but the settings aren't available.

image

**Comment by cklosowski** [comment]
@mindctrl i'll reverify, I thought I had one there that wasn't configured yet. I'll update when I find the issue.

**Comment by cklosowski** [comment]
@mindctrl if you have ONLY extensions that were not updated yet...(acquisition survey) does it show that set of settings, but no subsections?

**Comment by mindctrl** [comment]
@cklosowski yup, that works. I see the settings like this:

image

**Comment by JeroenSormani** [comment]
A FYI, this caused a issue in two of my plugins. I was loading a settings view (via the hook callback field type) using `require_once`, which resulted in it being loaded in the check if it had any settings, and not when actually displaying the settings.

I already fixed it by changing it to just `require` (probably better too), but thought it could be a learning moment for the future for both :smile:

**Comment by pippinsplugins** [comment]
@JeroenSormani Thanks for the headsup! We'll watch out for similar cases.

**Pull request merged**
