### PR TITLE
Dashicon as EDD media button

### PR DESCRIPTION
**Pull request by corvannoorloos**
I originally just wanted to update the EDD media button to make use of the WP Dashicon font, but also came across some inline styles and spaces used as indentation.

I hope it's ok I've added these in the same request.

38-new-post

38-new-post-mobile

I've tested the Add New Post, Add New Download and Downloads screen running WordPress 3.7 and 3.8 and 4.2 on Windows 7, Ubuntu 14.04.1 and iOS 8.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
I love the idea of doing this.

Initially your PR looks good. We can test further and get it in for 2.3.

**Comment by corvannoorloos** [comment]
Thanks, just let me know if I could do anything further :smiley:

**Comment by corvannoorloos** [comment]
@pippinsplugins would you mind if I also updated the remaining images? Would you prefer a request per image, or should I continue working on this request the way I've did above?

**Comment by pippinsplugins** [comment]
@corvannoorloos Go for it, but please make a separate pull request.

**Comment by pippinsplugins** [comment]
Turns out that WordPress core has decided to move away from Dashicons, so I'm not sure this should be done any more https://make.wordpress.org/design/2015/01/04/the-future-of-dashicons/

**Comment by corvannoorloos** [comment]
I wasn't aware of that, thanks. We'll see what happens next.

**Comment by corvannoorloos** [comment]
Followup on previous link https://make.wordpress.org/core/2015/06/11/moving-dashicons-from-an-icon-font-to-svg/

**Comment by nosegraze** [comment]
Do we know if there's been any movement on this? From what I can tell, the whole SVG project has been dead for over a year (unless there's more discussion I couldn't find). If that's the case, maybe this should be reconsidered?

**Comment by michaelbeil** [comment]
@easydigitaldownloads/core-devs do we want to open a new issue to address dashicons?

**Comment by pippinsplugins** [comment]
@michaelbeil we have one https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5033

**Comment by michaelbeil** [comment]
I know we have that issue, just was not sure if we want to address anything else dashicon-wise.

**Pull request closed without merging**
