### PR TITLE
Issue/4291

### PR DESCRIPTION
**Pull request by DevinWalker**
#4291

### CODE REVIEW

**Comment by pippinsplugins** [comment]
Looks good to me.

**Comment by cklosowski** [comment]
I think this should be `log in`. `login` references a username or identifier. `log in` references the action of logging in. Is that correct @mindctrl?

**Comment by pippinsplugins** [comment]
That is correct.

**Comment by michaelbeil** [comment]
Yes @cklosowski: http://public.wsu.edu/~brians/errors/login.html.

**Comment by cklosowski** [comment]
Going to merge and then fix that line.

**Pull request merged**
