### PR TITLE
Set flush_rewrite_rules to use false

### PR DESCRIPTION
**Pull request by chriscct7**
See #3414

### CODE REVIEW

**Comment by cklosowski** [comment]
Next time, maybe a single commit for this please? In case we have to revert, it makes it much easier to do.

**Comment by chriscct7** [comment]
Whenever GitHub implements either multifile single commits or git squash from their online interface, sure thing ;) Noticed + fixed it on the way to class on a phone.

**Comment by cklosowski** [comment]
Then next time, since this wasn't a 'has to be deployed now' thing, wait until you are at a computer and do it in a single commit.

**Comment by chriscct7** [comment]
It was something I just remembered thanks to a Twitter rant. Was just easier to get it done with so I wouldn't forget about it. I'll try to write it down next time

**Comment by cklosowski** [comment]
Since it was in a branch, we can squash it still :) once my CI passes for the Squash I'll merge

**Pull request merged**
