### PR TITLE
Added new filter edd_receipt_no_files_found_text.

### PR DESCRIPTION
**Pull request by danieliser**
Added new filter edd_receipt_no_files_found_text allowing filtering of the "No downloadable files found." message per $download_id.

### CODE REVIEW

**Comment by cklosowski** [comment]
@danieliser Is there something going on between the two commits that look exactly the same? And what was the ```merge``` commit? Just rebasing with master?

Otherwise, looks good.

**Comment by pippinsplugins** [comment]
Note: for organization's sake, please open a issue to describe the enhancement or bug and then open a PR that references the issue. Just makes it easier to keep track of everything.

**Comment by pippinsplugins** [comment]
@cklosowski Looks good to merge to me.

**Comment by danieliser** [comment]
No it was a typo, receipt was misspelled in the filter name. Thanks for the quick merge, will create issue to go with it next time.

**Pull request merged**
