### PR TITLE
Rename "Cyprus Island" to just "Cyprus".

### PR DESCRIPTION
**Pull request by dannyvankooten**
There's no "Cyprus Island", just "Cyprus". :)

### CODE REVIEW

**Comment by chriscct7** [comment]
Technically it's the "Republic of Cyprus" officially. I think we should rename it to that

**Comment by dannyvankooten** [comment]
Sorry but I definitely disagree. That would mean we'd have to change all countries as A LOT of them are republics, technically speaking. 

I think we should go with the most commonly used names. The list is fine, really, it's just that "Cyprus Island" [is not a thing](http://europa.eu/about-eu/countries/member-countries/).

**Comment by pippinsplugins** [comment]
Considering it's listed as `Cyprus` [here](http://europa.eu/about-eu/countries/member-countries/), I 'd say we leave it at that. Doesn't get much more official :)

**Comment by pippinsplugins** [comment]
We'll need to fix the unit tests on this.

**Comment by cklosowski** [comment]
I'm going to merge, and then fix the unit test on this

**Pull request merged**
