### PR TITLE
[WIP] Issue/7210 - Retain unique item ID's when migrating

### PR DESCRIPTION
**Pull request by JJJ**
Addressing #7210.

Proposed Changes:
- [x] The database API Query class requires a very small change to support this
- [x] The database API Table class should get auto-incrementor manipulation methods, in the event someone wants to (or needs to) manually adjust them
- [x] The migration API will require more tweaks and more testing to make sure it correctly addresses all of our above concerns

### CODE REVIEW

**Comment by cklosowski** [comment]
@mintplugins this seemed to work fine for me. all things migrated, the auto_increment was pre-defined to be 1 greater than the max edd_payment post type.

When you get a chance, can you please try this again?

**Comment by mintplugins** [comment]
Running another migration now...

**Comment by mintplugins** [comment]
Here's the results of my last 2 migration tests. I used the same database for both, and wiped out all tables completely before each migration:

Screen Shot 2019-04-30 at 5 47 37 PM

The second migration is the correct one, as the auto_increment ID used to create the new `refund` orders was set to a higher number than the highest payment ID pre-migration. 

It's possible that in the first migration something went wonky with my tables. I can't see any other reason for it. So I am okay to merge this now, but we should keep an eye on this happening when we do further migration tests in the future.

**Comment by mintplugins** [comment]
I wonder if we should migrate tax rates after discount codes so that they don't begin at 1:

Screen Shot 2019-05-01 at 3 29 32 PM

**Comment by cklosowski** [comment]
@mintplugins by setting the auto increment, it should take care of that. I'll have to re-test to verify what you're seeing.

**Comment by mintplugins** [comment]
After using wp cli to export my database things were correct after migration. My issues above must have been due to some sort of strange issue with the table migrated through Migrate DB Pro

**Pull request merged**
