### PR TITLE
Code for the Issue #3636

### PR DESCRIPTION
**Pull request by MythThrazz**
#3636

- Displaying the daterange filters on the Earnings by Category report
- Adding the daterange support for the class outputting the report
- Fixing the bug in the EDD_Payment_Stats class

### CODE REVIEW

**Comment by cklosowski** [comment]
Looks like the transients have been removed. This shouldn't happen. We need to cache the result set. This would probably mean making a hash of the arguments to get a string unique to that request.

**Comment by pippinsplugins** [comment]
@MythThrazz Did you see Chris's comment about the transients?

**Comment by MythThrazz** [comment]
Hi, 
Sorry for late reply, been busy. I'm working on some more fixes to this part, so I'll fix the transient and the naming convention and commit again.

**Comment by cklosowski** [comment]
Two issues left on my end:

There are a number of changes to the whitespace in this PR that don't fall in line with our core codebase...and it's against master.

Could you please bring your branch of this up to date with our `master` and re-submit the PR to `issue/3636`. I'm getting a bunch of notices and warnings with it currently, and while the overall idea of it seems right, I want it in a branch so I can merge your changes, and update where I see necessary.

This is a great 90% of the way there PR though. thanks @MythThrazz

**Pull request closed without merging**
