### PR TITLE
Use buttons in remove repeatable fields

### PR DESCRIPTION
**Pull request by samikeijonen**
In general links are for links when you actually go somewhere, buttons are for actions. This PR replaces links with buttons in remove repeatable fields. There is more details in issue #4343.

### CODE REVIEW

**Comment by samikeijonen** [comment]
In the bundle we have this button:

```
<button class="edd_remove_repeatable" data-type="file" style="background: url(<?php echo admin_url('/images/xit.gif'); ?>) no-repeat;"><span class="screen-reader-text"><?php printf( __( 'Remove bundle option %s', 'easy-digital-downloads' ), $key ); ?></span><span aria-hidden="true">&times;</span></button>
```

Is it possible to get bundle download name instead of just `$key`?

**Comment by pippinsplugins** [comment]
That might be possible but will likely require more javascript.

**Comment by samikeijonen** [comment]
Okay. No worries, it might be totally overkill in this situation. At least it's not the same text for all buttons.

**Comment by pippinsplugins** [comment]
Works great, merging into `release/2.6`.

**Pull request closed without merging**
