### PR TITLE
Add file sorting

### PR DESCRIPTION
**Pull request by ghost1227**
Issue #3760

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@ghost1227 this appears to work perfectly, nice. One small thing. The ID column needs updated when adding a new row: https://cloudup.com/cuJcTGcGYBm

It shows properly after saved but not when first created.

**Comment by pippinsplugins** [comment]
Nevermind, I just needed a refresh.

**Comment by cklosowski** [comment]
@ghost1227 can you take a look at rolling the latest 2.5 back into your branch? That way it'll possibly merge cleanly.

**Comment by ghost1227** [comment]
@cklosowski sure thing!

**Comment by cklosowski** [comment]
@ghost1227 ping. Can you get the most recent `release/2.5` merged back into your branch so this cleanly merges?

**Comment by ghost1227** [comment]
@pippinsplugins I'm pretty sure I got that rebase right... Works and passes unit tests!

**Comment by cklosowski** [comment]
Merging into 2.5 for more testing.

**Pull request merged**
